const STIX_TEMPLATES = {
    "attack-pattern": { type: "attack-pattern", name: "New Attack Pattern", color: "#ff5252" },
    "campaign": { type: "campaign", name: "New Campaign", color: "#d32f2f" },
    "course-of-action": { type: "course-of-action", name: "New Course of Action", color: "#4caf50" },
    "grouping": { type: "grouping", name: "New Grouping", color: "#9e9e9e" },
    "identity": { type: "identity", name: "New Identity", color: "#448aff" },
    "indicator": { type: "indicator", name: "New Indicator", color: "#ffc107" },
    "infrastructure": { type: "infrastructure", name: "New Infrastructure", color: "#00e676" },
    "intrusion-set": { type: "intrusion-set", name: "New Intrusion Set", color: "#f44336" },
    "location": { type: "location", name: "New Location", color: "#8bc34a" },
    "malware": { type: "malware", name: "New Malware", color: "#ffab40" },
    "malware-analysis": { type: "malware-analysis", color: "#ff9800" },
    "note": { type: "note", content: "New Note Content", color: "#fff176" },
    "observed-data": { type: "observed-data", color: "#00bcd4" },
    "opinion": { type: "opinion", color: "#ffeb3b" },
    "report": { type: "report", name: "New Threat Report", color: "#3f51b5" },
    "threat-actor": { type: "threat-actor", name: "New Threat Actor", color: "#e040fb" },
    "tool": { type: "tool", name: "New Tool", color: "#795548" },
    "vulnerability": { type: "vulnerability", name: "CVE-0000-0000", color: "#ff5722" }
};
