/**
 * stix_schema.js — STIX 2.1 Object Definitions & Schema
 * Standalone, no external dependencies.
 * OWASP: All data defined as constants; no eval; no innerHTML assignment of raw user data.
 */

'use strict';

const STIX_SCHEMA = (function () {

  // ─────────────────────────── Color palette per object category ───────────────────────────
  const COLORS = {
    sdo:  { bg: '#1a3a5c', border: '#4fc3f7', text: '#e3f2fd', icon: '#4fc3f7' },
    sro:  { bg: '#1a2e1a', border: '#81c784', text: '#e8f5e9', icon: '#81c784' },
    sco:  { bg: '#2e1a3a', border: '#ce93d8', text: '#f3e5f5', icon: '#ce93d8' },
    meta: { bg: '#3a2e1a', border: '#ffb74d', text: '#fff3e0', icon: '#ffb74d' },
  };

  // ─────────────────────────── STIX Domain Objects (SDO) ───────────────────────────
  const SDO_TYPES = [
    {
      type: 'attack-pattern',
      label: 'Attack Pattern',
      icon: '⚔',
      category: 'sdo',
      description: 'A type of TTP that describes ways adversaries attempt to compromise targets.',
      required: ['type', 'spec_version', 'id', 'created', 'modified', 'name'],
      fields: [
        { key: 'name', label: 'Name', type: 'text', required: true },
        { key: 'description', label: 'Description', type: 'textarea' },
        { key: 'aliases', label: 'Aliases', type: 'tags' },
        { key: 'kill_chain_phases', label: 'Kill Chain Phases', type: 'kill_chain' },
        { key: 'external_references', label: 'External References', type: 'ext_refs' },
      ],
    },
    {
      type: 'campaign',
      label: 'Campaign',
      icon: '🎯',
      category: 'sdo',
      description: 'A grouping of adversarial behaviors over a period of time with shared goals.',
      required: ['type', 'spec_version', 'id', 'created', 'modified', 'name'],
      fields: [
        { key: 'name', label: 'Name', type: 'text', required: true },
        { key: 'description', label: 'Description', type: 'textarea' },
        { key: 'aliases', label: 'Aliases', type: 'tags' },
        { key: 'first_seen', label: 'First Seen', type: 'datetime' },
        { key: 'last_seen', label: 'Last Seen', type: 'datetime' },
        { key: 'objective', label: 'Objective', type: 'text' },
      ],
    },
    {
      type: 'course-of-action',
      label: 'Course of Action',
      icon: '🛡',
      category: 'sdo',
      description: 'Actions taken to prevent an attack or respond to one.',
      required: ['type', 'spec_version', 'id', 'created', 'modified', 'name'],
      fields: [
        { key: 'name', label: 'Name', type: 'text', required: true },
        { key: 'description', label: 'Description', type: 'textarea' },
        { key: 'action_type', label: 'Action Type', type: 'text' },
        { key: 'os_execution_envs', label: 'OS Execution Envs', type: 'tags' },
        { key: 'action_bin', label: 'Action Binary', type: 'text' },
      ],
    },
    {
      type: 'grouping',
      label: 'Grouping',
      icon: '📂',
      category: 'sdo',
      description: 'Explicitly asserts that referenced STIX Objects have a shared context.',
      required: ['type', 'spec_version', 'id', 'created', 'modified', 'context', 'object_refs'],
      fields: [
        { key: 'name', label: 'Name', type: 'text' },
        { key: 'description', label: 'Description', type: 'textarea' },
        { key: 'context', label: 'Context', type: 'text', required: true },
        { key: 'object_refs', label: 'Object References', type: 'tags' },
      ],
    },
    {
      type: 'identity',
      label: 'Identity',
      icon: '🪪',
      category: 'sdo',
      description: 'Actual individuals, organizations, or groups, as well as classes of them.',
      required: ['type', 'spec_version', 'id', 'created', 'modified', 'name', 'identity_class'],
      fields: [
        { key: 'name', label: 'Name', type: 'text', required: true },
        { key: 'description', label: 'Description', type: 'textarea' },
        { key: 'roles', label: 'Roles', type: 'tags' },
        { key: 'identity_class', label: 'Identity Class', type: 'select',
          options: ['individual','group','system','organization','class','unknown'], required: true },
        { key: 'sectors', label: 'Sectors', type: 'tags' },
        { key: 'contact_information', label: 'Contact Information', type: 'textarea' },
      ],
    },
    {
      type: 'indicator',
      label: 'Indicator',
      icon: '🔍',
      category: 'sdo',
      description: 'Contains a pattern that can be used to detect suspicious or malicious activity.',
      required: ['type', 'spec_version', 'id', 'created', 'modified', 'name', 'indicator_types', 'pattern', 'pattern_type', 'valid_from'],
      fields: [
        { key: 'name', label: 'Name', type: 'text', required: true },
        { key: 'description', label: 'Description', type: 'textarea' },
        { key: 'indicator_types', label: 'Indicator Types', type: 'tags', required: true },
        { key: 'pattern', label: 'Pattern', type: 'textarea', required: true },
        { key: 'pattern_type', label: 'Pattern Type', type: 'select',
          options: ['stix','pcre','sigma','snort','suricata','yara'], required: true },
        { key: 'pattern_version', label: 'Pattern Version', type: 'text' },
        { key: 'valid_from', label: 'Valid From', type: 'datetime', required: true },
        { key: 'valid_until', label: 'Valid Until', type: 'datetime' },
        { key: 'kill_chain_phases', label: 'Kill Chain Phases', type: 'kill_chain' },
      ],
    },
    {
      type: 'infrastructure',
      label: 'Infrastructure',
      icon: '🖧',
      category: 'sdo',
      description: 'Systems, software services, and physical/virtual resources used by adversaries.',
      required: ['type', 'spec_version', 'id', 'created', 'modified', 'name', 'infrastructure_types'],
      fields: [
        { key: 'name', label: 'Name', type: 'text', required: true },
        { key: 'description', label: 'Description', type: 'textarea' },
        { key: 'infrastructure_types', label: 'Infrastructure Types', type: 'tags', required: true },
        { key: 'aliases', label: 'Aliases', type: 'tags' },
        { key: 'kill_chain_phases', label: 'Kill Chain Phases', type: 'kill_chain' },
        { key: 'first_seen', label: 'First Seen', type: 'datetime' },
        { key: 'last_seen', label: 'Last Seen', type: 'datetime' },
      ],
    },
    {
      type: 'intrusion-set',
      label: 'Intrusion Set',
      icon: '🕵',
      category: 'sdo',
      description: 'Grouped set of adversarial behaviors believed to have a common source.',
      required: ['type', 'spec_version', 'id', 'created', 'modified', 'name'],
      fields: [
        { key: 'name', label: 'Name', type: 'text', required: true },
        { key: 'description', label: 'Description', type: 'textarea' },
        { key: 'aliases', label: 'Aliases', type: 'tags' },
        { key: 'first_seen', label: 'First Seen', type: 'datetime' },
        { key: 'last_seen', label: 'Last Seen', type: 'datetime' },
        { key: 'goals', label: 'Goals', type: 'tags' },
        { key: 'resource_level', label: 'Resource Level', type: 'text' },
        { key: 'primary_motivation', label: 'Primary Motivation', type: 'text' },
        { key: 'secondary_motivations', label: 'Secondary Motivations', type: 'tags' },
      ],
    },
    {
      type: 'location',
      label: 'Location',
      icon: '📍',
      category: 'sdo',
      description: 'A geographic location such as a country, city, region, or coordinate.',
      required: ['type', 'spec_version', 'id', 'created', 'modified'],
      fields: [
        { key: 'name', label: 'Name', type: 'text' },
        { key: 'description', label: 'Description', type: 'textarea' },
        { key: 'latitude', label: 'Latitude', type: 'number' },
        { key: 'longitude', label: 'Longitude', type: 'number' },
        { key: 'precision', label: 'Precision (meters)', type: 'number' },
        { key: 'region', label: 'Region', type: 'text' },
        { key: 'country', label: 'Country (ISO 3166-1)', type: 'text' },
        { key: 'administrative_area', label: 'Administrative Area', type: 'text' },
        { key: 'city', label: 'City', type: 'text' },
        { key: 'street_address', label: 'Street Address', type: 'text' },
        { key: 'postal_code', label: 'Postal Code', type: 'text' },
      ],
    },
    {
      type: 'malware',
      label: 'Malware',
      icon: '🦠',
      category: 'sdo',
      description: 'A type of TTP, malicious code or software used to attack targets.',
      required: ['type', 'spec_version', 'id', 'created', 'modified', 'name', 'malware_types', 'is_family'],
      fields: [
        { key: 'name', label: 'Name', type: 'text', required: true },
        { key: 'description', label: 'Description', type: 'textarea' },
        { key: 'malware_types', label: 'Malware Types', type: 'tags', required: true },
        { key: 'is_family', label: 'Is Family', type: 'boolean', required: true },
        { key: 'aliases', label: 'Aliases', type: 'tags' },
        { key: 'kill_chain_phases', label: 'Kill Chain Phases', type: 'kill_chain' },
        { key: 'first_seen', label: 'First Seen', type: 'datetime' },
        { key: 'last_seen', label: 'Last Seen', type: 'datetime' },
        { key: 'os_execution_envs', label: 'OS Execution Envs', type: 'tags' },
        { key: 'architecture_execution_envs', label: 'Architecture Envs', type: 'tags' },
        { key: 'implementation_languages', label: 'Implementation Languages', type: 'tags' },
        { key: 'capabilities', label: 'Capabilities', type: 'tags' },
      ],
    },
    {
      type: 'malware-analysis',
      label: 'Malware Analysis',
      icon: '🔬',
      category: 'sdo',
      description: 'Static or dynamic analysis performed on a malware instance.',
      required: ['type', 'spec_version', 'id', 'created', 'modified', 'product', 'result'],
      fields: [
        { key: 'product', label: 'Product', type: 'text', required: true },
        { key: 'version', label: 'Version', type: 'text' },
        { key: 'host_vm_ref', label: 'Host VM Ref', type: 'text' },
        { key: 'operating_system_ref', label: 'OS Ref', type: 'text' },
        { key: 'installed_software_refs', label: 'Installed Software Refs', type: 'tags' },
        { key: 'configuration_version', label: 'Config Version', type: 'text' },
        { key: 'modules', label: 'Modules', type: 'tags' },
        { key: 'analysis_engine_version', label: 'Engine Version', type: 'text' },
        { key: 'analysis_definition_version', label: 'Definition Version', type: 'text' },
        { key: 'submitted', label: 'Submitted', type: 'datetime' },
        { key: 'analysis_started', label: 'Analysis Started', type: 'datetime' },
        { key: 'analysis_ended', label: 'Analysis Ended', type: 'datetime' },
        { key: 'result_name', label: 'Result Name', type: 'text' },
        { key: 'result', label: 'Result', type: 'select',
          options: ['malicious','suspicious','benign','unknown'], required: true },
      ],
    },
    {
      type: 'note',
      label: 'Note',
      icon: '📝',
      category: 'sdo',
      description: 'Adds non-analytical commentary or context to referenced STIX objects.',
      required: ['type', 'spec_version', 'id', 'created', 'modified', 'content', 'object_refs'],
      fields: [
        { key: 'abstract', label: 'Abstract', type: 'text' },
        { key: 'content', label: 'Content', type: 'textarea', required: true },
        { key: 'authors', label: 'Authors', type: 'tags' },
        { key: 'object_refs', label: 'Object References', type: 'tags', required: true },
      ],
    },
    {
      type: 'observed-data',
      label: 'Observed Data',
      icon: '👁',
      category: 'sdo',
      description: 'Information observed on systems or networks (e.g., IP, domain, file).',
      required: ['type', 'spec_version', 'id', 'created', 'modified', 'first_observed', 'last_observed', 'number_observed', 'object_refs'],
      fields: [
        { key: 'first_observed', label: 'First Observed', type: 'datetime', required: true },
        { key: 'last_observed', label: 'Last Observed', type: 'datetime', required: true },
        { key: 'number_observed', label: 'Number Observed', type: 'number', required: true },
        { key: 'object_refs', label: 'Object References', type: 'tags', required: true },
      ],
    },
    {
      type: 'opinion',
      label: 'Opinion',
      icon: '💬',
      category: 'sdo',
      description: 'An assessment of the correctness of information in a STIX Object.',
      required: ['type', 'spec_version', 'id', 'created', 'modified', 'opinion', 'object_refs'],
      fields: [
        { key: 'explanation', label: 'Explanation', type: 'textarea' },
        { key: 'authors', label: 'Authors', type: 'tags' },
        { key: 'opinion', label: 'Opinion', type: 'select',
          options: ['strongly-disagree','disagree','neutral','agree','strongly-agree'], required: true },
        { key: 'object_refs', label: 'Object References', type: 'tags', required: true },
      ],
    },
    {
      type: 'report',
      label: 'Report',
      icon: '📊',
      category: 'sdo',
      description: 'Collections of threat intelligence focused on one or more topics.',
      required: ['type', 'spec_version', 'id', 'created', 'modified', 'name', 'report_types', 'published', 'object_refs'],
      fields: [
        { key: 'name', label: 'Name', type: 'text', required: true },
        { key: 'description', label: 'Description', type: 'textarea' },
        { key: 'report_types', label: 'Report Types', type: 'tags', required: true },
        { key: 'published', label: 'Published', type: 'datetime', required: true },
        { key: 'object_refs', label: 'Object References', type: 'tags', required: true },
      ],
    },
    {
      type: 'threat-actor',
      label: 'Threat Actor',
      icon: '😈',
      category: 'sdo',
      description: 'Individuals, groups, or organizations believed to be operating with malicious intent.',
      required: ['type', 'spec_version', 'id', 'created', 'modified', 'name', 'threat_actor_types'],
      fields: [
        { key: 'name', label: 'Name', type: 'text', required: true },
        { key: 'description', label: 'Description', type: 'textarea' },
        { key: 'threat_actor_types', label: 'Threat Actor Types', type: 'tags', required: true },
        { key: 'aliases', label: 'Aliases', type: 'tags' },
        { key: 'first_seen', label: 'First Seen', type: 'datetime' },
        { key: 'last_seen', label: 'Last Seen', type: 'datetime' },
        { key: 'roles', label: 'Roles', type: 'tags' },
        { key: 'goals', label: 'Goals', type: 'tags' },
        { key: 'sophistication', label: 'Sophistication', type: 'text' },
        { key: 'resource_level', label: 'Resource Level', type: 'text' },
        { key: 'primary_motivation', label: 'Primary Motivation', type: 'text' },
        { key: 'secondary_motivations', label: 'Secondary Motivations', type: 'tags' },
        { key: 'personal_motivations', label: 'Personal Motivations', type: 'tags' },
      ],
    },
    {
      type: 'tool',
      label: 'Tool',
      icon: '🔧',
      category: 'sdo',
      description: 'Legitimate software that can be used by threat actors to attack targets.',
      required: ['type', 'spec_version', 'id', 'created', 'modified', 'name', 'tool_types'],
      fields: [
        { key: 'name', label: 'Name', type: 'text', required: true },
        { key: 'description', label: 'Description', type: 'textarea' },
        { key: 'tool_types', label: 'Tool Types', type: 'tags', required: true },
        { key: 'aliases', label: 'Aliases', type: 'tags' },
        { key: 'kill_chain_phases', label: 'Kill Chain Phases', type: 'kill_chain' },
        { key: 'tool_version', label: 'Tool Version', type: 'text' },
      ],
    },
    {
      type: 'vulnerability',
      label: 'Vulnerability',
      icon: '⚠',
      category: 'sdo',
      description: 'A mistake in software that can be directly used by a threat actor to gain access.',
      required: ['type', 'spec_version', 'id', 'created', 'modified', 'name'],
      fields: [
        { key: 'name', label: 'Name', type: 'text', required: true },
        { key: 'description', label: 'Description', type: 'textarea' },
        { key: 'external_references', label: 'External References (CVE)', type: 'ext_refs' },
      ],
    },
  ];

  // ─────────────────────────── STIX Relationship Objects (SRO) ───────────────────────────
  const SRO_TYPES = [
    {
      type: 'relationship',
      label: 'Relationship',
      icon: '↔',
      category: 'sro',
      description: 'Defines a directed relationship between two STIX objects.',
      required: ['type', 'spec_version', 'id', 'created', 'modified', 'relationship_type', 'source_ref', 'target_ref'],
      fields: [
        { key: 'relationship_type', label: 'Relationship Type', type: 'select',
          options: [
            'attributed-to','authored-by','beacons-to','belongs-to','communicates-with',
            'compromises','controls','cooperates-with','derived-from','downloads',
            'drops','exploits','has','hosts','impersonates','indicates','investigates',
            'is-related-to','located-at','mitigates','originates-from','owns',
            'remediates','targets','threatens','uses','variant-of','attributed-to',
          ], required: true },
        { key: 'description', label: 'Description', type: 'textarea' },
        { key: 'start_time', label: 'Start Time', type: 'datetime' },
        { key: 'stop_time', label: 'Stop Time', type: 'datetime' },
        { key: 'source_ref', label: 'Source Ref', type: 'text', required: true },
        { key: 'target_ref', label: 'Target Ref', type: 'text', required: true },
      ],
    },
    {
      type: 'sighting',
      label: 'Sighting',
      icon: '👀',
      category: 'sro',
      description: 'Records that a cyber threat indicator or other STIX content was observed.',
      required: ['type', 'spec_version', 'id', 'created', 'modified', 'sighting_of_ref'],
      fields: [
        { key: 'description', label: 'Description', type: 'textarea' },
        { key: 'first_seen', label: 'First Seen', type: 'datetime' },
        { key: 'last_seen', label: 'Last Seen', type: 'datetime' },
        { key: 'count', label: 'Count', type: 'number' },
        { key: 'sighting_of_ref', label: 'Sighting Of Ref', type: 'text', required: true },
        { key: 'observed_data_refs', label: 'Observed Data Refs', type: 'tags' },
        { key: 'where_sighted_refs', label: 'Where Sighted Refs', type: 'tags' },
        { key: 'summary', label: 'Summary', type: 'boolean' },
      ],
    },
  ];

  // ─────────────────────────── STIX Cyber Observables (SCO) ───────────────────────────
  const SCO_TYPES = [
    {
      type: 'artifact',
      label: 'Artifact',
      icon: '📦',
      category: 'sco',
      description: 'Binary data captured as a base64-encoded blob or URL reference.',
      required: ['type', 'id'],
      fields: [
        { key: 'mime_type', label: 'MIME Type', type: 'text' },
        { key: 'payload_bin', label: 'Payload (base64)', type: 'textarea' },
        { key: 'url', label: 'URL', type: 'text' },
        { key: 'hashes', label: 'Hashes (JSON)', type: 'json' },
        { key: 'encryption_algorithm', label: 'Encryption Algorithm', type: 'text' },
        { key: 'decryption_key', label: 'Decryption Key', type: 'text' },
      ],
    },
    {
      type: 'autonomous-system',
      label: 'Autonomous System',
      icon: '🌐',
      category: 'sco',
      description: 'An Autonomous System (AS) number.',
      required: ['type', 'id', 'number'],
      fields: [
        { key: 'number', label: 'AS Number', type: 'number', required: true },
        { key: 'name', label: 'Name', type: 'text' },
        { key: 'rir', label: 'RIR', type: 'text' },
      ],
    },
    {
      type: 'directory',
      label: 'Directory',
      icon: '📁',
      category: 'sco',
      description: 'Properties common to a file system directory.',
      required: ['type', 'id', 'path'],
      fields: [
        { key: 'path', label: 'Path', type: 'text', required: true },
        { key: 'path_enc', label: 'Path Encoding', type: 'text' },
        { key: 'ctime', label: 'Created', type: 'datetime' },
        { key: 'mtime', label: 'Modified', type: 'datetime' },
        { key: 'atime', label: 'Accessed', type: 'datetime' },
        { key: 'contains_refs', label: 'Contains Refs', type: 'tags' },
      ],
    },
    {
      type: 'domain-name',
      label: 'Domain Name',
      icon: '🌍',
      category: 'sco',
      description: 'A network domain name.',
      required: ['type', 'id', 'value'],
      fields: [
        { key: 'value', label: 'Domain', type: 'text', required: true },
        { key: 'resolves_to_refs', label: 'Resolves To Refs', type: 'tags' },
      ],
    },
    {
      type: 'email-addr',
      label: 'Email Address',
      icon: '✉',
      category: 'sco',
      description: 'A single email address.',
      required: ['type', 'id', 'value'],
      fields: [
        { key: 'value', label: 'Email Address', type: 'text', required: true },
        { key: 'display_name', label: 'Display Name', type: 'text' },
        { key: 'belongs_to_ref', label: 'Belongs To Ref', type: 'text' },
      ],
    },
    {
      type: 'email-message',
      label: 'Email Message',
      icon: '📨',
      category: 'sco',
      description: 'An email message instance.',
      required: ['type', 'id', 'is_multipart'],
      fields: [
        { key: 'is_multipart', label: 'Is Multipart', type: 'boolean', required: true },
        { key: 'date', label: 'Date', type: 'datetime' },
        { key: 'content_type', label: 'Content Type', type: 'text' },
        { key: 'from_ref', label: 'From Ref', type: 'text' },
        { key: 'sender_ref', label: 'Sender Ref', type: 'text' },
        { key: 'to_refs', label: 'To Refs', type: 'tags' },
        { key: 'cc_refs', label: 'CC Refs', type: 'tags' },
        { key: 'bcc_refs', label: 'BCC Refs', type: 'tags' },
        { key: 'message_id', label: 'Message ID', type: 'text' },
        { key: 'subject', label: 'Subject', type: 'text' },
        { key: 'received_lines', label: 'Received Lines', type: 'tags' },
        { key: 'body', label: 'Body', type: 'textarea' },
      ],
    },
    {
      type: 'file',
      label: 'File',
      icon: '📄',
      category: 'sco',
      description: 'A file on a file system.',
      required: ['type', 'id'],
      fields: [
        { key: 'name', label: 'Name', type: 'text' },
        { key: 'size', label: 'Size (bytes)', type: 'number' },
        { key: 'name_enc', label: 'Name Encoding', type: 'text' },
        { key: 'magic_number_hex', label: 'Magic Number (hex)', type: 'text' },
        { key: 'mime_type', label: 'MIME Type', type: 'text' },
        { key: 'ctime', label: 'Created', type: 'datetime' },
        { key: 'mtime', label: 'Modified', type: 'datetime' },
        { key: 'atime', label: 'Accessed', type: 'datetime' },
        { key: 'hashes', label: 'Hashes (JSON)', type: 'json' },
      ],
    },
    {
      type: 'ipv4-addr',
      label: 'IPv4 Address',
      icon: '🔌',
      category: 'sco',
      description: 'An IPv4 address expressed in CIDR notation.',
      required: ['type', 'id', 'value'],
      fields: [
        { key: 'value', label: 'IPv4 Address (CIDR)', type: 'text', required: true },
        { key: 'resolves_to_refs', label: 'Resolves To Refs', type: 'tags' },
        { key: 'belongs_to_refs', label: 'Belongs To Refs', type: 'tags' },
      ],
    },
    {
      type: 'ipv6-addr',
      label: 'IPv6 Address',
      icon: '🔗',
      category: 'sco',
      description: 'An IPv6 address expressed in CIDR notation.',
      required: ['type', 'id', 'value'],
      fields: [
        { key: 'value', label: 'IPv6 Address (CIDR)', type: 'text', required: true },
        { key: 'resolves_to_refs', label: 'Resolves To Refs', type: 'tags' },
        { key: 'belongs_to_refs', label: 'Belongs To Refs', type: 'tags' },
      ],
    },
    {
      type: 'mac-addr',
      label: 'MAC Address',
      icon: '📡',
      category: 'sco',
      description: 'A Media Access Control (MAC) address.',
      required: ['type', 'id', 'value'],
      fields: [
        { key: 'value', label: 'MAC Address', type: 'text', required: true },
      ],
    },
    {
      type: 'mutex',
      label: 'Mutex',
      icon: '🔒',
      category: 'sco',
      description: 'A mutual exclusion (mutex) object.',
      required: ['type', 'id', 'name'],
      fields: [
        { key: 'name', label: 'Name', type: 'text', required: true },
      ],
    },
    {
      type: 'network-traffic',
      label: 'Network Traffic',
      icon: '📶',
      category: 'sco',
      description: 'Network traffic originating from a source and going to a destination.',
      required: ['type', 'id', 'dst_ref', 'protocols'],
      fields: [
        { key: 'start', label: 'Start', type: 'datetime' },
        { key: 'end', label: 'End', type: 'datetime' },
        { key: 'is_active', label: 'Is Active', type: 'boolean' },
        { key: 'src_ref', label: 'Source Ref', type: 'text' },
        { key: 'dst_ref', label: 'Destination Ref', type: 'text', required: true },
        { key: 'src_port', label: 'Source Port', type: 'number' },
        { key: 'dst_port', label: 'Destination Port', type: 'number' },
        { key: 'protocols', label: 'Protocols', type: 'tags', required: true },
        { key: 'src_byte_count', label: 'Src Byte Count', type: 'number' },
        { key: 'dst_byte_count', label: 'Dst Byte Count', type: 'number' },
        { key: 'src_packets', label: 'Src Packets', type: 'number' },
        { key: 'dst_packets', label: 'Dst Packets', type: 'number' },
      ],
    },
    {
      type: 'process',
      label: 'Process',
      icon: '⚙',
      category: 'sco',
      description: 'Common properties of an instance of a computer program.',
      required: ['type', 'id'],
      fields: [
        { key: 'is_hidden', label: 'Is Hidden', type: 'boolean' },
        { key: 'pid', label: 'PID', type: 'number' },
        { key: 'created_time', label: 'Created Time', type: 'datetime' },
        { key: 'cwd', label: 'CWD', type: 'text' },
        { key: 'command_line', label: 'Command Line', type: 'text' },
        { key: 'image_ref', label: 'Image Ref', type: 'text' },
        { key: 'parent_ref', label: 'Parent Ref', type: 'text' },
        { key: 'child_refs', label: 'Child Refs', type: 'tags' },
        { key: 'opened_connections_refs', label: 'Opened Connections Refs', type: 'tags' },
      ],
    },
    {
      type: 'software',
      label: 'Software',
      icon: '💿',
      category: 'sco',
      description: 'A high-level software object.',
      required: ['type', 'id', 'name'],
      fields: [
        { key: 'name', label: 'Name', type: 'text', required: true },
        { key: 'cpe', label: 'CPE', type: 'text' },
        { key: 'swid', label: 'SWID', type: 'text' },
        { key: 'languages', label: 'Languages', type: 'tags' },
        { key: 'vendor', label: 'Vendor', type: 'text' },
        { key: 'version', label: 'Version', type: 'text' },
      ],
    },
    {
      type: 'url',
      label: 'URL',
      icon: '🔗',
      category: 'sco',
      description: 'A Uniform Resource Locator (URL).',
      required: ['type', 'id', 'value'],
      fields: [
        { key: 'value', label: 'URL', type: 'text', required: true },
      ],
    },
    {
      type: 'user-account',
      label: 'User Account',
      icon: '👤',
      category: 'sco',
      description: 'An instance of any type of user account, including OS, device, messaging, etc.',
      required: ['type', 'id'],
      fields: [
        { key: 'user_id', label: 'User ID', type: 'text' },
        { key: 'credential', label: 'Credential', type: 'text' },
        { key: 'account_login', label: 'Account Login', type: 'text' },
        { key: 'account_type', label: 'Account Type', type: 'text' },
        { key: 'display_name', label: 'Display Name', type: 'text' },
        { key: 'is_service_account', label: 'Is Service Account', type: 'boolean' },
        { key: 'is_privileged', label: 'Is Privileged', type: 'boolean' },
        { key: 'can_escalate_privs', label: 'Can Escalate Privs', type: 'boolean' },
        { key: 'is_disabled', label: 'Is Disabled', type: 'boolean' },
        { key: 'account_created', label: 'Account Created', type: 'datetime' },
        { key: 'account_expires', label: 'Account Expires', type: 'datetime' },
        { key: 'credential_last_changed', label: 'Credential Last Changed', type: 'datetime' },
        { key: 'account_first_login', label: 'First Login', type: 'datetime' },
        { key: 'account_last_login', label: 'Last Login', type: 'datetime' },
      ],
    },
    {
      type: 'windows-registry-key',
      label: 'Windows Registry Key',
      icon: '🗝',
      category: 'sco',
      description: 'The properties of a Windows registry key.',
      required: ['type', 'id'],
      fields: [
        { key: 'key', label: 'Registry Key', type: 'text' },
        { key: 'values', label: 'Values (JSON)', type: 'json' },
        { key: 'modified_time', label: 'Modified Time', type: 'datetime' },
        { key: 'creator_user_ref', label: 'Creator User Ref', type: 'text' },
        { key: 'number_of_subkeys', label: 'Number of Subkeys', type: 'number' },
      ],
    },
    {
      type: 'x509-certificate',
      label: 'X.509 Certificate',
      icon: '📜',
      category: 'sco',
      description: 'An X.509 certificate, as defined by ITU recommendation X.509.',
      required: ['type', 'id'],
      fields: [
        { key: 'is_self_signed', label: 'Is Self-Signed', type: 'boolean' },
        { key: 'hashes', label: 'Hashes (JSON)', type: 'json' },
        { key: 'version', label: 'Version', type: 'text' },
        { key: 'serial_number', label: 'Serial Number', type: 'text' },
        { key: 'signature_algorithm', label: 'Signature Algorithm', type: 'text' },
        { key: 'issuer', label: 'Issuer', type: 'text' },
        { key: 'validity_not_before', label: 'Valid From', type: 'datetime' },
        { key: 'validity_not_after', label: 'Valid Until', type: 'datetime' },
        { key: 'subject', label: 'Subject', type: 'text' },
        { key: 'subject_public_key_algorithm', label: 'Public Key Algorithm', type: 'text' },
        { key: 'subject_public_key_modulus', label: 'Public Key Modulus', type: 'text' },
        { key: 'subject_public_key_exponent', label: 'Public Key Exponent', type: 'number' },
      ],
    },
  ];

  // ─────────────────────────── Meta Objects ───────────────────────────
  const META_TYPES = [
    {
      type: 'marking-definition',
      label: 'Marking Definition',
      icon: '🏷',
      category: 'meta',
      description: 'Specifies data marking for STIX objects (TLP, etc.).',
      required: ['type', 'spec_version', 'id', 'created', 'definition_type', 'definition'],
      fields: [
        { key: 'name', label: 'Name', type: 'text' },
        { key: 'definition_type', label: 'Definition Type', type: 'select',
          options: ['tlp','statement'], required: true },
        { key: 'definition', label: 'Definition (JSON)', type: 'json', required: true },
      ],
    },
    {
      type: 'extension-definition',
      label: 'Extension Definition',
      icon: '🧩',
      category: 'meta',
      description: 'Defines an extension to the STIX specification.',
      required: ['type', 'spec_version', 'id', 'created', 'modified', 'created_by_ref', 'name', 'schema', 'version', 'extension_types'],
      fields: [
        { key: 'name', label: 'Name', type: 'text', required: true },
        { key: 'description', label: 'Description', type: 'textarea' },
        { key: 'schema', label: 'Schema URL', type: 'text', required: true },
        { key: 'version', label: 'Version', type: 'text', required: true },
        { key: 'extension_types', label: 'Extension Types', type: 'tags', required: true },
        { key: 'extension_properties', label: 'Extension Properties', type: 'tags' },
      ],
    },
  ];

  // ─────────────────────────── Palette sections ───────────────────────────
  const PALETTE_SECTIONS = [
    { id: 'sdo', label: 'Domain Objects (SDO)', types: SDO_TYPES },
    { id: 'sro', label: 'Relationship Objects (SRO)', types: SRO_TYPES },
    { id: 'sco', label: 'Cyber Observables (SCO)', types: SCO_TYPES },
    { id: 'meta', label: 'Meta Objects', types: META_TYPES },
  ];

  // ─────────────────────────── All types map ───────────────────────────
  const ALL_TYPES_MAP = {};
  [...SDO_TYPES, ...SRO_TYPES, ...SCO_TYPES, ...META_TYPES].forEach(t => {
    ALL_TYPES_MAP[t.type] = t;
  });

  // ─────────────────────────── Common fields shared by all SDO/SRO ───────────────────────────
  const COMMON_FIELDS = [
    { key: 'spec_version', label: 'Spec Version', type: 'text', default: '2.1' },
    { key: 'created_by_ref', label: 'Created By Ref', type: 'text' },
    { key: 'revoked', label: 'Revoked', type: 'boolean' },
    { key: 'labels', label: 'Labels', type: 'tags' },
    { key: 'confidence', label: 'Confidence (0-100)', type: 'number' },
    { key: 'lang', label: 'Language', type: 'text' },
    { key: 'object_marking_refs', label: 'Object Marking Refs', type: 'tags' },
  ];

  // ─────────────────────────── Valid relationship type pairs ───────────────────────────
  const VALID_RELATIONSHIPS = {
    'attack-pattern': {
      targets: ['identity', 'location', 'vulnerability'],
      uses: ['malware', 'tool'],
    },
    'campaign': {
      attributed_to: ['intrusion-set', 'threat-actor'],
      compromises: ['infrastructure'],
      originates_from: ['location'],
      targets: ['identity', 'location', 'vulnerability'],
      uses: ['attack-pattern', 'infrastructure', 'malware', 'tool'],
    },
    'course-of-action': {
      investigates: ['indicator'],
      mitigates: ['attack-pattern', 'indicator', 'malware', 'tool', 'vulnerability'],
      remediates: ['malware', 'vulnerability'],
    },
    'indicator': {
      based_on: ['observed-data'],
      indicates: ['attack-pattern', 'campaign', 'infrastructure', 'intrusion-set', 'malware', 'threat-actor', 'tool'],
    },
    'malware': {
      authored_by: ['threat-actor', 'intrusion-set'],
      beacons_to: ['infrastructure'],
      communicates_with: ['infrastructure', 'ipv4-addr', 'ipv6-addr', 'domain-name', 'url'],
      controls: ['malware'],
      downloads: ['file', 'malware', 'tool'],
      drops: ['file', 'malware', 'tool'],
      exploits: ['vulnerability'],
      originates_from: ['location'],
      targets: ['identity', 'infrastructure', 'location', 'vulnerability'],
      uses: ['attack-pattern', 'infrastructure', 'malware', 'tool'],
      variant_of: ['malware'],
    },
    'threat-actor': {
      attributed_to: ['identity'],
      compromises: ['infrastructure'],
      hosts: ['infrastructure', 'tool'],
      impersonates: ['identity'],
      located_at: ['location'],
      owns: ['infrastructure'],
      targets: ['identity', 'location', 'vulnerability'],
      uses: ['attack-pattern', 'infrastructure', 'malware', 'tool'],
    },
    'tool': {
      delivers: ['malware'],
      drops: ['malware'],
      has: ['vulnerability'],
      targets: ['identity', 'infrastructure', 'location', 'vulnerability'],
    },
    'intrusion-set': {
      attributed_to: ['threat-actor'],
      compromises: ['infrastructure'],
      hosts: ['infrastructure'],
      originates_from: ['location'],
      owns: ['infrastructure'],
      targets: ['identity', 'location', 'vulnerability'],
      uses: ['attack-pattern', 'infrastructure', 'malware', 'tool'],
    },
    'infrastructure': {
      communicates_with: ['infrastructure', 'ipv4-addr', 'ipv6-addr', 'domain-name', 'url'],
      consists_of: ['infrastructure', 'ipv4-addr', 'ipv6-addr', 'domain-name', 'url', 'file', 'software'],
      controls: ['infrastructure', 'malware'],
      delivers: ['malware'],
      has: ['vulnerability'],
      hosts: ['tool', 'malware'],
      located_at: ['location'],
      uses: ['infrastructure'],
    },
  };

  return {
    COLORS,
    PALETTE_SECTIONS,
    ALL_TYPES_MAP,
    COMMON_FIELDS,
    VALID_RELATIONSHIPS,
    SDO_TYPES,
    SRO_TYPES,
    SCO_TYPES,
    META_TYPES,
  };
})();
