"use strict";
function proc(id,name,knowledgeArea,instructions,outputs,domainTags){return {id,name,knowledgeArea,instructions,outputs,domainTags,status:"not_started",owner:"",dueDate:"",notes:"",decisions:"",risks:"",checklist:"",attachments:[]}}
const TEMPLATE=[
    {
      id: "initiating",
      name: "Initiating",
      summary: "Authorize the project or phase and identify the initial stakeholder landscape.",
      processes: [
        proc(
          "initiating__develop_project_charter",
          "Develop Project Charter",
          "Integration",
          "Formally authorize the project or phase. Capture the purpose, measurable objectives, high-level scope, assumptions, constraints, success criteria, sponsor, and the project manager's authority.",
          "Charter draft; business case linkage; success criteria; high-level assumptions and constraints; initial milestone and funding view.",
          "Planning, Stakeholder, Delivery"
        ),
        proc(
          "initiating__identify_stakeholders",
          "Identify Stakeholders",
          "Stakeholder",
          "Identify individuals, groups, and organizations affected by the work. Record their interests, influence, expectations, and preferred engagement methods.",
          "Stakeholder register; influence and interest analysis; initial engagement approach; escalation paths.",
          "Stakeholder, Team, Delivery"
        )
      ]
    },
    {
      id: "planning",
      name: "Planning",
      summary: "Establish the integrated plan, baselines, and management approaches for the work.",
      processes: [
        proc("planning__develop_project_management_plan","Develop Project Management Plan","Integration","Combine subsidiary plans into one integrated management plan. Decide how work will be directed, measured, controlled, and changed.","Integrated project management plan; baseline strategy; governance cadence; tailoring decisions.","Planning, Measurement, Development Approach & Life Cycle"),
        proc("planning__plan_scope_management","Plan Scope Management","Scope","Define how scope will be elicited, documented, validated, and controlled so the team knows how scope decisions will be made.","Scope management approach; scope change rules; validation method; backlog or requirements governance.","Planning, Delivery"),
        proc("planning__collect_requirements","Collect Requirements","Scope","Elicit, analyze, prioritize, and document stakeholder needs, constraints, interfaces, compliance obligations, and acceptance expectations.","Requirements set; acceptance criteria; traceability basis; assumptions and exclusions.","Stakeholder, Planning, Delivery"),
        proc("planning__define_scope","Define Scope","Scope","Turn the approved requirements into a clear scope statement that explains included work, exclusions, boundaries, and deliverables.","Scope statement; product and project boundaries; exclusions list; deliverable descriptions.","Planning, Delivery"),
        proc("planning__create_wbs","Create WBS","Scope","Break deliverables and project work into manageable components so work can be estimated, assigned, tracked, and controlled.","Work breakdown structure; WBS dictionary; control accounts; work package definitions.","Planning, Project Work"),
        proc("planning__plan_schedule_management","Plan Schedule Management","Schedule","Define how the schedule will be built, maintained, tracked, reported, and re-baselined when necessary.","Schedule management approach; calendar assumptions; reporting cadence; scheduling rules.","Planning, Measurement"),
        proc("planning__define_activities","Define Activities","Schedule","Identify the specific activities needed to complete each work package or backlog item at the level needed for control.","Activity list; activity attributes; milestone candidates; decomposition notes.","Planning, Project Work"),
        proc("planning__sequence_activities","Sequence Activities","Schedule","Determine logical relationships among activities, including dependencies, constraints, and opportunities for parallel work.","Network logic; dependency map; lead and lag assumptions; sequencing decisions.","Planning, Project Work"),
        proc("planning__estimate_activity_durations","Estimate Activity Durations","Schedule","Estimate the work periods needed for each activity using expert input, historical data, capacity, and uncertainty assumptions.","Duration estimates; basis of estimate; uncertainty notes; reserve rationale.","Planning, Measurement, Uncertainty"),
        proc("planning__develop_schedule","Develop Schedule","Schedule","Build the schedule model, critical path or flow view, milestones, reserve placement, and approved target dates.","Approved schedule baseline; milestone plan; forecast logic; schedule presentation views.","Planning, Measurement, Delivery"),
        proc("planning__plan_cost_management","Plan Cost Management","Cost","Define how costs will be estimated, budgeted, approved, tracked, forecasted, and reported.","Cost management approach; control thresholds; reporting format; estimating rules.","Planning, Measurement"),
        proc("planning__estimate_costs","Estimate Costs","Cost","Estimate labor, material, contract, licensing, tool, contingency, and other costs required to deliver the work.","Cost estimates; basis of estimate; estimating assumptions; confidence ranges.","Planning, Measurement, Uncertainty"),
        proc("planning__determine_budget","Determine Budget","Cost","Aggregate approved cost estimates into an authorized budget and funding profile with reserves and control thresholds.","Cost baseline; funding requirements; reserve allocation; cash flow view.","Planning, Measurement"),
        proc("planning__plan_quality_management","Plan Quality Management","Quality","Define the quality objectives, standards, review methods, metrics, and prevention activities needed to meet expectations.","Quality management approach; quality criteria; review and test strategy; metrics list.","Planning, Delivery, Measurement"),
        proc("planning__plan_resource_management","Plan Resource Management","Resource","Determine how people, facilities, equipment, and materials will be acquired, organized, developed, and released.","Resource management approach; roles and responsibilities; staffing strategy; release plan.","Planning, Team, Project Work"),
        proc("planning__estimate_activity_resources","Estimate Activity Resources","Resource","Estimate the type and quantity of people, skills, tools, equipment, and materials needed for each activity.","Resource requirements; skill profile; resource calendars; estimating assumptions.","Planning, Team, Project Work"),
        proc("planning__plan_communications_management","Plan Communications Management","Communications","Define what information will be shared, with whom, by whom, in what format, and at what cadence.","Communications plan; audience matrix; meeting cadence; reporting templates.","Stakeholder, Planning, Measurement"),
        proc("planning__plan_risk_management","Plan Risk Management","Risk","Define the methods, thresholds, roles, and timing for identifying, analyzing, responding to, and monitoring uncertainty.","Risk management approach; scoring rules; response categories; reserve philosophy.","Uncertainty, Planning, Measurement"),
        proc("planning__identify_risks","Identify Risks","Risk","Identify threats and opportunities that could affect objectives, along with causes, triggers, owners, and possible responses.","Risk register; assumptions under review; trigger list; opportunity list.","Uncertainty, Planning"),
        proc("planning__perform_qualitative_risk_analysis","Perform Qualitative Risk Analysis","Risk","Prioritize risks using probability, impact, urgency, detectability, and other agreed criteria so attention goes to what matters most.","Prioritized risk list; qualitative assessments; watchlist; analysis notes.","Uncertainty, Measurement"),
        proc("planning__perform_quantitative_risk_analysis","Perform Quantitative Risk Analysis","Risk","Where needed, analyze overall project uncertainty numerically using ranges, scenarios, or simulation to inform decisions.","Quantitative analysis results; confidence levels; exposure estimates; reserve recommendations.","Uncertainty, Measurement, Planning"),
        proc("planning__plan_risk_responses","Plan Risk Responses","Risk","Define strategies and actions to avoid, mitigate, transfer, accept, exploit, enhance, or share risk and opportunity.","Risk response plan; fallback actions; contingency triggers; risk action owners.","Uncertainty, Planning, Project Work"),
        proc("planning__plan_procurement_management","Plan Procurement Management","Procurement","Decide what to buy, when, how, from whom, and under what commercial and legal terms.","Procurement strategy; make-or-buy notes; statement of work outline; sourcing schedule.","Planning, Stakeholder, Project Work"),
        proc("planning__plan_stakeholder_engagement","Plan Stakeholder Engagement","Stakeholder","Define tailored engagement strategies for each stakeholder or group based on interest, influence, needs, and desired support.","Stakeholder engagement plan; target engagement states; messaging strategy; sponsor actions.","Stakeholder, Team, Planning")
      ]
    },
    {
      id: "executing",
      name: "Executing",
      summary: "Perform the work, manage the team, deliver outputs, and execute engagement and response plans.",
      processes: [
        proc("executing__direct_and_manage_project_work","Direct and Manage Project Work","Integration","Lead the planned work, coordinate contributors, use approved resources, and create the project deliverables.","Work performance data; deliverables; issue log updates; implementation records.","Project Work, Delivery, Team"),
        proc("executing__manage_project_knowledge","Manage Project Knowledge","Integration","Use existing organizational knowledge and capture new lessons, decisions, and know-how while the work is happening.","Lessons learned updates; decision rationale; reusable knowledge artifacts; knowledge sharing actions.","Team, Project Work, Measurement"),
        proc("executing__manage_quality","Manage Quality","Quality","Audit and improve processes so the team prevents defects and consistently produces work that can meet acceptance criteria.","Process improvement actions; quality assurance findings; audit results; updated working methods.","Delivery, Measurement, Project Work"),
        proc("executing__acquire_resources","Acquire Resources","Resource","Obtain the people, equipment, materials, environments, and services needed to execute the approved plan.","Assigned resources; onboarding actions; vendor or internal commitments; resource availability updates.","Team, Project Work"),
        proc("executing__develop_team","Develop Team","Resource","Improve competencies, trust, collaboration, and shared understanding so the team can perform more effectively.","Training actions; team agreements; coaching notes; performance improvement actions.","Team, Leadership, Project Work"),
        proc("executing__manage_team","Manage Team","Resource","Track performance, resolve conflict, remove impediments, provide feedback, and adjust assignments so the team can deliver.","Performance feedback; issue resolutions; staffing adjustments; recognition actions.","Team, Leadership, Project Work"),
        proc("executing__manage_communications","Manage Communications","Communications","Create, distribute, store, retrieve, and confirm project information so the right people receive useful information at the right time.","Status communications; meeting records; distribution logs; updated communication artifacts.","Stakeholder, Team, Measurement"),
        proc("executing__implement_risk_responses","Implement Risk Responses","Risk","Carry out agreed risk response actions, contingency triggers, opportunity actions, and fallback plans as conditions require.","Completed response actions; trigger status; contingency usage; response effectiveness notes.","Uncertainty, Project Work"),
        proc("executing__conduct_procurements","Conduct Procurements","Procurement","Solicit bids or proposals, evaluate responses, negotiate terms, and award agreements to selected sellers.","Signed agreements; selection records; proposal evaluations; procurement decisions.","Stakeholder, Project Work, Delivery"),
        proc("executing__manage_stakeholder_engagement","Manage Stakeholder Engagement","Stakeholder","Work with stakeholders to build support, address concerns, manage expectations, and sustain productive relationships.","Engagement actions; issue resolutions; updated stakeholder sentiments; support commitments.","Stakeholder, Team, Delivery")
      ]
    },
    {
      id: "monitoring_and_controlling",
      name: "Monitoring & Controlling",
      summary: "Measure performance, compare against plan, manage change, and keep the work aligned to objectives.",
      processes: [
        proc("monitoring_and_controlling__monitor_and_control_project_work","Monitor and Control Project Work","Integration","Track, review, and report overall performance against the plan so corrective and preventive action can be taken promptly.","Performance reports; forecast updates; corrective actions; preventive actions.","Measurement, Planning, Project Work"),
        proc("monitoring_and_controlling__perform_integrated_change_control","Perform Integrated Change Control","Integration","Review change requests, analyze impacts, decide approvals, and maintain alignment among baselines and plans.","Approved or rejected changes; change log; baseline updates; decision records.","Planning, Measurement, Stakeholder"),
        proc("monitoring_and_controlling__validate_scope","Validate Scope","Scope","Review completed deliverables with authorized stakeholders to obtain formal acceptance or document needed rework.","Accepted deliverables; rejection reasons; sign-off records; action items.","Delivery, Stakeholder, Measurement"),
        proc("monitoring_and_controlling__control_scope","Control Scope","Scope","Monitor the status of project and product scope and control changes to the scope baseline or approved backlog.","Scope variance analysis; change requests; updated scope records; trend notes.","Planning, Measurement, Delivery"),
        proc("monitoring_and_controlling__control_schedule","Control Schedule","Schedule","Track schedule performance, analyze variances, update forecasts, and implement actions to recover or protect dates.","Schedule forecasts; variance analysis; recovery actions; updated calendars and dates.","Measurement, Planning, Project Work"),
        proc("monitoring_and_controlling__control_costs","Control Costs","Cost","Measure cost performance, analyze variances, update forecasts, and control authorized spending.","Cost forecasts; variance analysis; reserve usage; corrective cost actions.","Measurement, Planning"),
        proc("monitoring_and_controlling__control_quality","Control Quality","Quality","Inspect deliverables and results to confirm they meet defined quality criteria and acceptance expectations.","Inspection results; defect log; rework requests; acceptance evidence.","Delivery, Measurement"),
        proc("monitoring_and_controlling__control_resources","Control Resources","Resource","Ensure assigned resources are available, used effectively, protected, and realigned as project needs change.","Resource utilization data; corrective actions; release changes; issue escalation.","Team, Measurement, Project Work"),
        proc("monitoring_and_controlling__monitor_communications","Monitor Communications","Communications","Evaluate whether communications are timely, clear, useful, and reaching the intended audiences.","Communication effectiveness findings; stakeholder feedback; updated communication actions.","Stakeholder, Measurement"),
        proc("monitoring_and_controlling__monitor_risks","Monitor Risks","Risk","Track identified risks, new risks, residual risk, response effectiveness, and overall uncertainty exposure over time.","Updated risk register; response effectiveness notes; new risks; reserve consumption data.","Uncertainty, Measurement"),
        proc("monitoring_and_controlling__control_procurements","Control Procurements","Procurement","Manage contracts, supplier performance, claims, deliverable acceptance, invoices, and procurement changes.","Vendor performance records; contract changes; claims log; acceptance and payment records.","Stakeholder, Measurement, Delivery"),
        proc("monitoring_and_controlling__monitor_stakeholder_engagement","Monitor Stakeholder Engagement","Stakeholder","Assess current stakeholder attitudes and engagement levels and adjust strategies when support or alignment changes.","Engagement assessments; updated strategies; escalations; sponsor action list.","Stakeholder, Measurement, Team")
      ]
    },
    {
      id: "closing",
      name: "Closing",
      summary: "Formally complete the project or phase, transition ownership, and preserve learning.",
      processes: [
        proc("closing__close_project_or_phase","Close Project or Phase","Integration","Confirm that all required work is complete, hand off accepted outputs, close contracts, release resources, and archive the record.","Final acceptance; transition package; closeout report; archived records; lessons learned summary.","Delivery, Team, Measurement, Stakeholder")
      ]
    }
  ];
const TYPES=["girs","fcrs","iers","dirs","pirs","sirs"], PRIORITIES=new Set(["Passive","Low","Medium","High"]), FORBIDDEN=new Set(["__proto__","prototype","constructor"]);
const SCOPE=["Requirements validation","Source selection","Collection configuration","Information extraction","Relevance scoring","Intelligence analysis","Product generation","Distribution workflow","Analyst training","Pilot production cycle","Operational transition"];
const OUT=["Continuous managed intelligence service","Incident response","Penetration testing","Malware reverse engineering","Dark-web collection","Security monitoring","Endpoint deployment","SIEM implementation","Threat-actor attribution","Remediation implementation"];
const DELIVERABLES=["Approved intelligence requirements","Collection plan","Source register","Extraction and normalization specification","Relevance scoring model","Intelligence-product templates","Analyst decision guide","Distribution and escalation matrix","Pilot intelligence products","Training materials","Operating procedure","Transition package"];
let cti=null,step=0,relationshipWarnings=[];
const $=id=>document.getElementById(id), text=v=>String(v??"").replace(/\r\n?/g,"\n");
function el(tag,txt,attrs={}){const n=document.createElement(tag);if(txt!==undefined)n.textContent=text(txt);for(const [k,v] of Object.entries(attrs)){if(k==="class")n.className=v;else n.setAttribute(k,text(v))}return n}
function add(p,...c){p.append(...c);return p} function clear(p){p.replaceChildren();return p}
function inspect(v,d=0,s={n:0}){if(d>12)throw Error("JSON nesting exceeds limit");if(v===null||["string","number","boolean"].includes(typeof v)){if(typeof v==="string"&&v.length>10000)throw Error("JSON string exceeds limit");if(typeof v==="number"&&!Number.isFinite(v))throw Error("Invalid number");return}if(typeof v!=="object")throw Error("Unsupported JSON value");if(Array.isArray(v)&&v.length>1000)throw Error("Array exceeds limit");for(const k of Object.keys(v)){if(++s.n>20000)throw Error("Too many JSON properties");if(FORBIDDEN.has(k))throw Error("Unsafe property name");inspect(v[k],d+1,s)}}
function validateCTI(o){inspect(o);if(!o||typeof o!=="object"||Array.isArray(o))throw Error("Root must be an object");for(const t of TYPES)if(!Array.isArray(o[t]))throw Error(`Missing ${t} array`);const ids={};relationshipWarnings=[];for(const t of TYPES){ids[t]=new Set();o[t].forEach((x,i)=>{if(!x||typeof x!=="object"||Array.isArray(x))throw Error(`Invalid ${t} item ${i+1}`);for(const k of Object.keys(x))if(!["id","priority","req","desc","link","coll","team","scope","dtype","output","dep","linkgir","linkfcr","datareq"].includes(k))throw Error(`Unexpected property ${k} in ${t}`);if(typeof x.id!=="string"||!x.id.trim())throw Error(`Missing ID in ${t}`);if(ids[t].has(x.id))throw Error(`Duplicate ID ${x.id}`);ids[t].add(x.id);if(typeof x.req!=="string"||!x.req.trim())throw Error(`Missing requirement text for ${x.id}`);if(!PRIORITIES.has(x.priority))throw Error(`Invalid priority for ${x.id}`)})}o.fcrs.forEach(x=>{if(x.link&&!ids.girs.has(x.link))relationshipWarnings.push(`${x.id} links to missing GIR ${x.link}`)});o.iers.forEach(x=>{if(x.link&&!ids.girs.has(x.link))relationshipWarnings.push(`${x.id} links to missing GIR ${x.link}`)});o.dirs.forEach(x=>{if(x.linkgir&&!ids.girs.has(x.linkgir))relationshipWarnings.push(`${x.id} links to missing GIR ${x.linkgir}`);if(x.linkfcr&&!ids.fcrs.has(x.linkfcr))relationshipWarnings.push(`${x.id} links to missing FCR ${x.linkfcr}`)});return structuredClone(o)}
function checks(host,items,prefix,defaults=true){const root=$(host);items.forEach((x,i)=>{const lab=el("label"),cb=el("input",undefined,{type:"checkbox",id:`${prefix}${i}`});cb.checked=defaults;add(lab,cb,document.createTextNode(" "+x));add(root,lab)})}
function selected(prefix,items){return items.filter((x,i)=>$(`${prefix}${i}`).checked)}
function renderImport(){const r=clear($("importSummary"));if(!cti)return;add(r,el("div","CTI file validated.",{class:"ok"}));const p=el("p");TYPES.forEach(t=>add(p,el("span",`${t.toUpperCase()}: ${cti[t].length}`,{class:"pill"})));add(r,p);if(relationshipWarnings.length)add(r,el("div",relationshipWarnings.join("\n"),{class:"warn"}))}
function renderReview(){const root=clear($("requirements")),sum=clear($("reviewSummary"));if(!cti){add(sum,el("div","Import CTI JSON first.",{class:"warn"}));return}add(sum,el("div",relationshipWarnings.length?`${relationshipWarnings.length} relationship warning(s).`:"All explicit CTI relationships resolve.",{class:relationshipWarnings.length?"warn":"ok"}));TYPES.forEach(t=>{add(root,el("h3",t.toUpperCase()));cti[t].forEach(x=>{const c=el("div",undefined,{class:"card"}),h=el("div",undefined,{class:"req-head"});add(h,el("strong",`${x.id}: ${x.req}`),el("span",x.priority,{class:"pill"}));add(c,h,el("div",x.desc||"No description",{class:"small"}));add(root,c)})})}
function setup(){checks("scopeOptions",SCOPE,"scope",true);checks("outOptions",OUT,"out",false);checks("deliverableOptions",DELIVERABLES,"del",true)}
function form(){return {name:text($("projectName").value).trim(),version:text($("projectVersion").value).trim(),sponsor:text($("sponsor").value).trim(),manager:text($("manager").value).trim(),ctiOwner:text($("ctiOwner").value).trim(),approver:text($("approver").value).trim(),startDate:$("startDate").value,endDate:$("endDate").value,objective:text($("objective").value).trim(),scope:selected("scope",SCOPE),out:selected("out",OUT),deliverables:selected("del",DELIVERABLES),acceptance:text($("acceptance").value).trim(),collectionOwner:text($("collectionOwner").value).trim(),analysisOwner:text($("analysisOwner").value).trim(),reviewer:text($("reviewer").value).trim(),distributionOwner:text($("distributionOwner").value).trim(),cadence:$("cadence").value,handling:$("handling").value,tools:text($("tools").value).trim(),constraints:text($("constraints").value).trim()}}
function clone(o){return structuredClone(o)} function projectProcess(state,id){for(const g of state.groups)for(const p of g.processes)if(p.id===id)return p;throw Error(`Missing canonical process ${id}`)}
function lines(arr){return arr.filter(Boolean).join("\n")} function reqLines(){const a=[];TYPES.forEach(t=>cti[t].forEach(x=>a.push(`${x.id} [${x.priority}] ${x.req}${x.desc?` | ${x.desc}`:""}`)));return a.join("\n")}
function provenance(origin,sources,review="Required"){return `[BRIDGE PROVENANCE]\nOrigin: ${origin}\nSource: ${sources}\nUser review: ${review}`}
function buildProject(){if(!cti)throw Error("Import CTI JSON first");const f=form(),now=new Date().toISOString(),state={schemaVersion:"1.1",createdAt:now,updatedAt:now,meta:{name:f.name,sponsor:f.sponsor,manager:f.manager,version:f.version,objective:f.objective},groups:clone(TEMPLATE)};for(const g of state.groups)for(const p of g.processes){p.status="not_started";p.owner="";p.dueDate="";p.notes="";p.decisions="";p.risks="";p.checklist="";p.attachments=[]}
 const charter=projectProcess(state,"initiating__develop_project_charter");charter.owner=f.manager;charter.dueDate=f.startDate;charter.notes=lines([provenance("Directly derived and user supplied",`CTI arrays and bridge setup`),"OBJECTIVE",f.objective,"IN SCOPE",f.scope.join("; ")||"TBD","OUT OF SCOPE",f.out.join("; ")||"TBD","PRIORITIZED QUESTIONS",cti.pirs.map(x=>`${x.id}: ${x.req}`).join("\n")]);charter.outputs+="\nProject-specific deliverables: "+(f.deliverables.join("; ")||"TBD");charter.decisions=lines([`Sponsor/approving function: ${f.sponsor||"TBD"}`,`Requirements approver: ${f.approver||"TBD"}`]);charter.risks=f.constraints||"TBD: Validate constraints, dependencies, and budget limits.";
 const stakeholders=projectProcess(state,"initiating__identify_stakeholders");stakeholders.owner=f.manager;stakeholders.notes=lines([provenance("Generated proposal","FCR teams and setup roles"),...new Set([f.sponsor,f.manager,f.ctiOwner,f.approver,f.collectionOwner,f.analysisOwner,f.reviewer,f.distributionOwner,...cti.fcrs.map(x=>x.team)].filter(Boolean))]);
 const collect=projectProcess(state,"planning__collect_requirements");collect.owner=f.approver;collect.notes=provenance("Directly derived","All CTI requirements")+"\n"+reqLines();collect.checklist="[ ] Validate GIRs\n[ ] Validate FCR-to-GIR relationships\n[ ] Validate IER dependencies\n[ ] Validate DIR source availability\n[ ] Confirm PIR decision owners\n[ ] Confirm SIR feasibility\n[ ] Approve requirements baseline";collect.risks=relationshipWarnings.join("\n");
 const scope=projectProcess(state,"planning__define_scope");scope.owner=f.manager;scope.notes=lines([provenance("User supplied","Bridge setup"),"IN SCOPE",f.scope.join("; ")||"TBD","OUT OF SCOPE",f.out.join("; ")||"TBD"]);scope.outputs+="\nAcceptance criteria: "+(f.acceptance||"TBD");
 const wbs=projectProcess(state,"planning__create_wbs");wbs.checklist=f.scope.map((x,i)=>`${i+1}. ${x}`).join("\n");wbs.notes=provenance("Generated proposal","Selected scope");
 const acts=projectProcess(state,"planning__define_activities");acts.owner=f.manager;acts.checklist=[...cti.fcrs.map(x=>`${x.id}: identify sources and configure collection for ${x.req}`),...cti.iers.map(x=>`${x.id}: define extraction for ${x.req}`),...cti.dirs.map(x=>`${x.id}: validate data availability for ${x.datareq||x.req}`),...cti.sirs.map(x=>`${x.id}: define analytical procedure for ${x.req}`)].join("\n");acts.notes=provenance("Generated proposal","FCR, IER, DIR, and SIR mapping");
 const seq=projectProcess(state,"planning__sequence_activities");seq.notes="Proposed dependency chain: Governance → requirements approval → source selection → collection → extraction → relevance scoring → product generation → pilot → evaluation → transition.";
 const sched=projectProcess(state,"planning__develop_schedule");sched.owner=f.manager;sched.notes=lines([`Start: ${f.startDate||"TBD"}`,`Required completion: ${f.endDate||"TBD"}`,`Requirements review cadence: ${f.cadence||"TBD"}`]);
 const comm=projectProcess(state,"planning__plan_communications_management");comm.owner=f.distributionOwner;comm.notes=lines([provenance("User supplied","Bridge setup"),`Handling: ${f.handling}`,`Distribution owner: ${f.distributionOwner||"TBD"}`,`Product reviewer: ${f.reviewer||"TBD"}`]);comm.checklist="[ ] Define urgent threshold\n[ ] Define routine delivery cadence\n[ ] Approve distribution list\n[ ] Confirm handling markings\n[ ] Define feedback mechanism";
 const quality=projectProcess(state,"planning__plan_quality_management");quality.owner=f.reviewer;quality.notes="Acceptance criteria:\n"+(f.acceptance||"TBD");quality.checklist="[ ] Relevant to approved requirement\n[ ] Source identified\n[ ] Fact and assessment separated\n[ ] Confidence stated\n[ ] Recipient identified\n[ ] Recommended action is realistic";
 const resources=projectProcess(state,"planning__plan_resource_management");resources.notes=lines([`Operational CTI owner: ${f.ctiOwner||"TBD"}`,`Collection: ${f.collectionOwner||"TBD"}`,`Analysis: ${f.analysisOwner||"TBD"}`,`Review: ${f.reviewer||"TBD"}`,`Distribution: ${f.distributionOwner||"TBD"}`]);
 const risk=projectProcess(state,"planning__identify_risks");risk.risks=lines([relationshipWarnings.length?relationshipWarnings.join("\n"):"No broken CTI relationships detected.",f.constraints,(!f.ctiOwner?"TBD: Operational CTI owner not assigned.":""),(!f.approver?"TBD: Requirements approver not assigned.":"")]);
 const procure=projectProcess(state,"planning__plan_procurement_management");procure.notes=lines([`Approved tools/sources: ${f.tools||"TBD"}`,`Constraints: ${f.constraints||"TBD"}`]);
 const direct=projectProcess(state,"executing__direct_and_manage_project_work");direct.owner=f.manager;direct.checklist=f.scope.map(x=>`[ ] ${x}`).join("\n");
 const knowledge=projectProcess(state,"executing__manage_project_knowledge");knowledge.owner=f.ctiOwner;knowledge.checklist="[ ] Maintain requirements change log\n[ ] Record source lessons\n[ ] Record product feedback\n[ ] Preserve decisions and rationale\n[ ] Maintain reusable templates";
 const manageComm=projectProcess(state,"executing__manage_communications");manageComm.owner=f.distributionOwner;manageComm.notes=`Handling: ${f.handling}`;
 const monitor=projectProcess(state,"monitoring_and_controlling__monitor_and_control_project_work");monitor.owner=f.manager;monitor.dueDate=f.endDate;monitor.checklist="[ ] Review milestones\n[ ] Review blocked CTI requirements\n[ ] Review source onboarding\n[ ] Review pilot delivery\n[ ] Review acceptance evidence\n[ ] Review transition readiness";
 const change=projectProcess(state,"monitoring_and_controlling__perform_integrated_change_control");change.owner=f.approver;change.checklist="[ ] Review new or changed GIR/PIR/FCR\n[ ] Review technology/vendor changes\n[ ] Review recipient or product changes\n[ ] Review geography or scope expansion\n[ ] Record approval decision";
 const validate=projectProcess(state,"monitoring_and_controlling__validate_scope");validate.owner=f.approver;validate.checklist=f.deliverables.map(x=>`[ ] Accept: ${x}`).join("\n");validate.notes="Acceptance criteria:\n"+(f.acceptance||"TBD");
 const cq=projectProcess(state,"monitoring_and_controlling__control_quality");cq.owner=f.reviewer;cq.checklist=quality.checklist;
 const mr=projectProcess(state,"monitoring_and_controlling__monitor_risks");mr.owner=f.ctiOwner;mr.notes=`Review cadence: ${f.cadence||"TBD"}`;mr.risks=risk.risks;
 const close=projectProcess(state,"closing__close_project_or_phase");close.owner=f.manager;close.dueDate=f.endDate;close.checklist=f.deliverables.map(x=>`[ ] Delivered and accepted: ${x}`).join("\n")+"\n[ ] Operational owner confirmed\n[ ] Open risks transferred\n[ ] Sensitive working files transferred or deleted\n[ ] Lessons learned captured";
 return state}
function mappingRows(){return [["GIR/PIR","Develop Project Charter","notes, outputs"],["All CTI objects","Collect Requirements","notes, checklist"],["FCR/IER/DIR/SIR","Define Activities","checklist"],["Selected scope","Define Scope / Create WBS","notes, checklist"],["Setup roles","Stakeholders / Resources / Communications","owner, notes"],["Acceptance criteria","Quality / Validate Scope","notes, checklist"],["Warnings and constraints","Identify Risks / Monitor Risks","risks"],["Deliverables","Validate Scope / Close Project","checklist"]]}
function renderMapping(){const root=clear($("mapping")),table=el("table"),head=el("tr");["Source","PMBOK destination","Fields"].forEach(x=>add(head,el("th",x)));add(table,head);mappingRows().forEach(r=>{const tr=el("tr");r.forEach(x=>add(tr,el("td",x)));add(table,tr)});add(root,table,el("div","Every generated process remains not_started. Missing governance decisions remain blank or are marked TBD.",{class:"notice"}))}
function validateProject(state){const errs=[];if(state.schemaVersion!=="1.1")errs.push("schemaVersion must be 1.1");if(!state.meta||typeof state.meta!=="object")errs.push("Missing meta");if(!Array.isArray(state.groups)||state.groups.length!==TEMPLATE.length)errs.push("Incorrect process groups");else TEMPLATE.forEach((g,i)=>{const x=state.groups[i];if(!x||x.id!==g.id)errs.push(`Group mismatch at ${g.id}`);else if(x.processes.length!==g.processes.length)errs.push(`Process count mismatch in ${g.id}`);else g.processes.forEach((p,j)=>{if(x.processes[j].id!==p.id)errs.push(`Process ID mismatch: ${p.id}`);if(!["not_started","in_progress","done","blocked"].includes(x.processes[j].status))errs.push(`Invalid status: ${p.id}`)})});return errs}
function renderValidation(){const root=clear($("validation"));if(!cti){add(root,el("div","Import CTI JSON first.",{class:"bad"}));return}const f=form(),missing=[];if(!f.name)missing.push("Project name");if(!f.version)missing.push("Revision");if(!f.sponsor)missing.push("Sponsor");if(!f.manager)missing.push("Project manager");if(!f.objective)missing.push("Business objective");let errs=[];try{errs=validateProject(buildProject())}catch(e){errs=[e.message]}if(missing.length)add(root,el("div","Required setup missing: "+missing.join(", "),{class:"bad"}));if(errs.length)add(root,el("div","PMBOK compatibility errors: "+errs.join("; "),{class:"bad"}));if(!missing.length&&!errs.length)add(root,el("div","Ready to export. Canonical PMBOK structure validated.",{class:"ok"}));if(relationshipWarnings.length)add(root,el("div","Non-blocking CTI relationship warnings: "+relationshipWarnings.join("; "),{class:"warn"}));$("exportProject").disabled=missing.length>0||errs.length>0}
function download(obj,name){const blob=new Blob([JSON.stringify(obj,null,2)],{type:"application/json"}),a=el("a");a.href=URL.createObjectURL(blob);a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function show(i){step=Math.max(0,Math.min(4,i));document.querySelectorAll(".step").forEach((x,n)=>x.classList.toggle("active",n===step));document.querySelectorAll("nav button").forEach((x,n)=>x.classList.toggle("active",n===step));$("prev").disabled=step===0;$("next").disabled=step===4;if(step===1)renderReview();if(step===3)renderMapping();if(step===4)renderValidation();window.scrollTo(0,0)}
function init(){setup();document.querySelectorAll("nav button").forEach((b,i)=>b.addEventListener("click",()=>show(i)));$("prev").addEventListener("click",()=>show(step-1));$("next").addEventListener("click",()=>show(step+1));$("ctiFile").addEventListener("change",e=>{const f=e.target.files[0];if(!f)return;if(f.size>5*1024*1024){alert("File exceeds 5 MB");return}const r=new FileReader();r.onload=()=>{try{cti=validateCTI(JSON.parse(r.result));$("status").textContent="CTI loaded";renderImport();const org=(cti.girs[0]?.desc||"").match(/Mission:\s*([^.]*)/i);if(org&&!$("projectName").value)$("projectName").value="Client CTI Capability Implementation"}catch(err){cti=null;$("status").textContent="Import failed";alert("Import failed: "+err.message)}finally{e.target.value=""}};r.onerror=()=>alert("File could not be read");r.readAsText(f)});$("exportProject").addEventListener("click",()=>{const p=buildProject(),errs=validateProject(p);if(errs.length){alert(errs.join("\n"));return}download(p,(p.meta.name||"cti-project").replace(/[^a-z0-9._ -]/gi,"-")+".json")});$("exportBridge").addEventListener("click",()=>download({schema:"cti-project-bridge-session",version:"1.0",cti,setup:form(),relationshipWarnings},"cti-project-bridge-session.json"));show(0)}
init();