
'use strict';
const MODEL_VERSION='4.0'; const STORAGE_KEY='nonprofitRiskWizard.v4';
const STEPS=[...document.querySelectorAll('.step')]; let stepIndex=0;
const actors=[['opportunist','The opportunist','Runs automated attacks broadly; wants encryption payment or account access.'],['fraudster','The payment fraudster','Uses public organizational details to create a convincing payment request.'],['former','The person who used to be here','A former employee, volunteer, contractor, or board member with lingering access.'],['aggrieved','The aggrieved party','May target reputation, accounts, or staff details because of a dispute.'],['accident','Nobody at all','Accidental sharing, lost devices, misdirected email, or a vendor breach.']];
const assets=['Donor names, addresses, giving history','Donor payment details or bank info','Records about the people we serve','Health, immigration, or family details','Employee records, payroll, SSNs','Grant applications and funder correspondence','Board minutes and internal deliberations','Our bank accounts and payment ability','Our website and public reputation','Volunteer contact lists'];
const domainQs=[['domains','What domain names do we own?','Check renewal charges; include old campaign domains.'],['registrar','Who is the registrar, and who can log in?','Use the renewal receipt.'],['expiry','What happens when the domain expires?','Record the expiry date and a 60-day warning.'],['emailHome','Where does email actually live?','Business service, web host, or personal accounts.'],['spoofing','Can outsiders send email as us?','Confirm whether DMARC is enforced; if nobody knows, record Not sure.']];
const systemSeed=['Email / file storage','Donor database or CRM','Donation / payment processor','Website and hosting','Accounting software','Payroll','Bank','Social media accounts','Email newsletter tool','Event or volunteer software','Cloud storage outside the above'];
const uncomfortable=['Is there any account everyone shares? If yes, which?','Is any password written in a document, spreadsheet, or pinned message? Where?','Has anyone left in the last two years whose access was never explicitly removed?','Does anyone use the same password at work and at home?','Is there a system only one person knows how to access? Which and who?','If that person were unreachable for two weeks, what could not be done?'];
const personal=['Personal email has a second sign-in step','Personal email recovery options are current and controlled','Phone carrier account has a PIN or port-out lock','Work password is not reused on personal accounts','Old personal email addresses are not recovery contacts for important accounts'];
const travel=['Home Wi-Fi and router administrator passwords were changed from defaults','Devices holding work email lock automatically','Organization banking is not performed on a shared or family computer'];
const sectors=['Humanitarian','Human rights','Advocacy','Journalism / media','Healthcare','Education','Faith-based','Community services','Democracy / elections','Legal services','Research','Arts / culture','Environmental','International development','Other'];
const incidents=['Fake email requesting money','Stolen account or password','Malware','Ransomware or extortion','Website compromise','Website outage or DDoS','Impersonation','Harassment','Doxxing or personal-data exposure','Lost or stolen device','Vendor security incident','Unauthorized access','None known','Other'];
const recipients=['General staff member','Internal IT staff','Volunteer IT','Managed service provider','Executive director','Board member','Security professional','Other'];
const capabilities=['Change account settings','Reset passwords','Install updates','Update firewall or network equipment','Check logs','Run technical queries','Modify website','Contact vendor or provider','Isolate a device','No direct technical action'];
const deliveries=['Urgent email','Normal email','Weekly digest','Ticket','Phone or SMS for emergencies','Send to IT provider'];
const products=['Plain-language action alert','Step-by-step remediation','Technical advisory for IT provider','Awareness bulletin','Machine-readable indicators'];
const PATHS=[
{id:'P1',n:'Payment redirected after an email account is taken over',i:5,l:4,raise:'largePayments'}, {id:'P2',n:'A password reused from another breach still works here',i:4,l:4}, {id:'P3',n:'A lookalike domain sends a convincing fake invoice',i:5,l:3,raise:'largePayments'}, {id:'P4',n:'Donor records exported from an unprotected platform',i:5,l:3,raise:'onlineDonations'}, {id:'P5',n:'Ransomware with no recoverable backup',i:5,l:3}, {id:'P6',n:'Website altered to skim card details or deface the page',i:4,l:3,raise:'onlineDonations'}, {id:'P7',n:'Someone who left still has access',i:4,l:3,raise:'more10'}, {id:'P8',n:'A shared password in a document opens several systems',i:4,l:4}, {id:'P9',n:"Leadership personal email resets work accounts",i:5,l:3}, {id:'P10',n:'Organization work occurs on an unmanaged personal device',i:3,l:4,raise:'mixedEmail'}, {id:'P11',n:'Public personal details make a fraud call believable',i:3,l:4}, {id:'P12',n:'A shared folder is readable by anyone with the link',i:4,l:3,raise:'clientRecords'}, {id:'P13',n:'One compromised account controls everything',i:5,l:3,raise:'mixedEmail'}, {id:'P14',n:'A lost or stolen device contains unencrypted files',i:3,l:3,raise:'clientRecords'}, {id:'P15',n:'A vendor is breached and notice arrives late',i:4,l:3}, {id:'P16',n:"A board member's account authorizes something",i:4,l:3,raise:'largePayments'}];
const CONTROLS=[
{id:'C1',q:'Every organization email account requires a second sign-in step',done:'Every account, no exceptions, enforced by policy.',tier:0,h:3,c:'$0',r:{P1:.55,P2:.6,P5:.2,P6:.15,P9:.3,P13:.35}},
{id:'C3',q:'Everyone uses a password manager with a unique password for every account',done:'Everyone uses it and the old password spreadsheet is deleted, including versions and trash.',tier:0,h:4,c:'low',r:{P1:.2,P2:.6,P4:.35,P8:.5,P9:.3,P13:.2}},
{id:'C6',q:'Backups exist and a file has actually been restored from one',done:'One copy is offline or immutable; a restore was opened this quarter.',tier:0,h:6,c:'low',r:{P5:.65}},
{id:'C5',q:'Payment changes are confirmed by phone before money moves',done:'Written rule uses a number already on file and applies above a defined threshold.',tier:0,h:2,c:'$0',r:{P1:.7,P3:.7,P11:.3,P16:.55}},
{id:'C18',q:'Everyone knows who to call in the first hour of a problem',done:'Printed card includes bank, IT, insurer, board chair, and reporting contacts.',tier:0,h:2,c:'$0',r:{P1:.25,P4:.15,P5:.2}},
{id:'C2',q:'Donation platform or donor database requires a second sign-in step',done:'Enforced for all users after shared accounts are eliminated.',tier:1,h:2,c:'$0',r:{P2:.4,P4:.6,P15:.15}},
{id:'C4',q:'The domain prevents outsiders from sending email that appears to come from it',done:'SPF and DKIM are valid; DMARC is moved to reject after an observation period.',tier:1,h:4,c:'$0',r:{P1:.15,P3:.45}},
{id:'C7',q:'Laptops and phones update automatically and encrypt storage',done:'Enabled on every device touching organization data, including personal devices with work email.',tier:1,h:4,c:'$0',r:{P5:.4,P10:.5,P14:.6}},
{id:'C8',q:'Access is removed the same day someone leaves',done:'Named owner runs a written checklist within 24 hours, including a retroactive review.',tier:1,h:2,c:'$0',r:{P7:.7}},
{id:'C9',q:'Shared logins are avoided and passwords are not kept in documents',done:'Every account maps to a person; unavoidable shared credentials are managed and rotated.',tier:1,h:4,c:'$0',r:{P7:.3,P8:.65}},
{id:'C15',q:'Every device locks with a PIN, password, or biometric',done:'Automatic lock after five minutes on all devices touching organization email.',tier:1,h:1,c:'$0',r:{P10:.35,P14:.4}},
{id:'C10',q:'Administrators use separate accounts for administrative work',done:'No more than two full admins; each uses a normal account for daily work.',tier:2,h:4,c:'$0',r:{P4:.3,P6:.2,P7:.25,P12:.3,P13:.6}},
{id:'C11',q:'Website is updated or hosted where updates are managed',done:'A named update owner, managed hosting, or a static site; unused plugins removed.',tier:2,h:5,c:'low',r:{P6:.6}},
{id:'C12',q:'Shared files visible to anyone with the link have been reviewed',done:'Link-sharing report reviewed, defaults restricted, annual re-check scheduled.',tier:2,h:4,c:'$0',r:{P8:.25,P10:.15,P12:.65}},
{id:'C17',q:'Everyone gets a short annual briefing on fake emails and payment fraud',done:'Thirty-minute briefing includes real examples, volunteers, board, and no-penalty reporting.',tier:2,h:3,c:'$0',r:{P1:.25,P3:.3,P5:.2,P11:.35,P16:.3}},
{id:'C19',q:'Records no longer needed are deleted on a schedule',done:'Written retention schedule checked against obligations and actually executed.',tier:2,h:4,c:'$0',r:{P4:.2,P12:.25,P15:.3}},
{id:'C13',q:"Director and board chair personal accounts are protected",done:'Second step, current recovery options, carrier port-out PIN, and old recovery addresses removed.',tier:3,h:3,c:'$0',r:{P9:.6,P16:.45}},
{id:'C14',q:'Leadership home addresses and phone numbers have been removed from data broker sites',done:'Search performed, opt-outs submitted, and 60-day re-check planned.',tier:3,h:5,c:'paid',r:{P11:.45}},
{id:'C16',q:'A list identifies vendors holding data and the contact at each',done:'List includes what they hold, contact, renewal date, and notification commitment.',tier:3,h:3,c:'$0',r:{P15:.4}},
{id:'C20',q:'One named person is responsible at board level',done:'Twice-yearly review, agenda item, and budget line appear in minutes.',tier:3,h:2,c:'$0',r:{P16:.2}}];
let data={meta:{modelVersion:MODEL_VERSION,created:new Date().toISOString(),updated:null},responses:{},tables:{systems:systemSeed.map(x=>({system:x,holds:'',admin:'',others:'',mfa:''})),vendors:[{},{},{}],accounts:[{},{}]}};
function node(tag,text,attrs={}){const n=document.createElement(tag);if(text!==undefined&&text!==null)n.textContent=String(text);for(const [k,v] of Object.entries(attrs)){if(k==='class')n.className=v;else n.setAttribute(k,String(v))}return n}function clear(el){el.replaceChildren();return el}function add(p,...children){p.append(...children);return p}const FORBIDDEN_KEYS=new Set(['__proto__','prototype','constructor']);function inspectTree(v,d=0,s={n:0}){if(d>10)throw new Error('Import nesting too deep');if(v===null||['string','number','boolean'].includes(typeof v)){if(typeof v==='string'&&v.length>5000)throw new Error('Imported value too long');if(typeof v==='number'&&!Number.isFinite(v))throw new Error('Invalid number');return}if(typeof v!=='object')throw new Error('Unsupported value type');if(Array.isArray(v)&&v.length>500)throw new Error('Imported array too large');for(const k of Object.keys(v)){if(++s.n>10000)throw new Error('Too many properties');if(FORBIDDEN_KEYS.has(k))throw new Error('Unsafe property name');inspectTree(v[k],d+1,s)}}
function safeText(v){return typeof v==='string'||typeof v==='number'||typeof v==='boolean'?String(v):''} function h(v){return safeText(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function get(path){return path.split('.').reduce((o,k)=>o&&Object.prototype.hasOwnProperty.call(o,k)?o[k]:undefined,data.responses)} function markDirty(){document.getElementById('saveStatus').textContent='Changes not saved'} function set(path,val){const ks=path.split('.');let o=data.responses;ks.slice(0,-1).forEach(k=>{if(!Object.prototype.hasOwnProperty.call(o,k)||typeof o[k]!=='object'||o[k]===null||Array.isArray(o[k]))o[k]={};o=o[k]});o[ks.at(-1)]=val;markDirty();if(path.startsWith('controls.')||path.startsWith('context.'))updateAll();else if(path.startsWith('intake.'))updateGate();else if(path.startsWith('threat.')||path.startsWith('plan.')){const c=calc();renderReport(c,tier(),recommendations(c))}}
function renderStatic(){
 document.getElementById('stepsNav').innerHTML=STEPS.map((s,i)=>`<button type="button" data-step="${i}">${i+1}. ${h(s.dataset.title)}</button>`).join('');
 document.getElementById('actors').innerHTML=actors.map(([id,n,d])=>`<fieldset><legend>${h(n)}</legend><p>${h(d)}</p><div class="grid2"><label>Plausibility (1–5)<select data-key="threat.actors.${id}.score"><option value="">Choose</option>${[1,2,3,4,5].map(x=>`<option>${x}</option>`).join('')}</select></label><label>Why<textarea data-key="threat.actors.${id}.why" maxlength="1200"></textarea></label></div></fieldset>`).join('');
 document.getElementById('assetsBody').innerHTML=assets.map((a,i)=>`<tr><th scope="row">${h(a)}</th><td><input aria-label="We hold ${h(a)}" type="checkbox" data-key="threat.assets.${i}.held"></td><td><textarea aria-label="Who gets hurt: ${h(a)}" data-key="threat.assets.${i}.public" maxlength="1200"></textarea></td><td><textarea aria-label="What stops: ${h(a)}" data-key="threat.assets.${i}.outage" maxlength="1200"></textarea></td><td><input aria-label="Crown jewel: ${h(a)}" type="checkbox" data-key="threat.assets.${i}.crown"></td></tr>`).join('');
 document.getElementById('domainQuestions').innerHTML=domainQs.map(([id,q,help])=>`<div class="field"><label>${h(q)}<textarea data-key="surface.${id}" maxlength="2000"></textarea></label><div class="small">${h(help)}</div></div>`).join('');
 document.getElementById('uncomfortable').innerHTML=uncomfortable.map((q,i)=>`<div class="field"><label>${h(q)}<textarea data-key="surface.uncomfortable.${i}" maxlength="1600"></textarea></label></div>`).join('');
 document.getElementById('personalChecks').innerHTML=personal.map((q,i)=>`<label><input type="checkbox" data-key="surface.personal.${i}"> ${h(q)}</label><br>`).join('');
 document.getElementById('travelChecks').innerHTML=travel.map((q,i)=>`<label><input type="checkbox" data-key="surface.travel.${i}"> ${h(q)}</label><br>`).join('');
 document.getElementById('sectorChecks').innerHTML=sectors.map((q,i)=>`<label><input type="checkbox" data-key="profile.sectors.${i}"> ${h(q)}</label>`).join('');
 document.getElementById('incidentChecks').innerHTML=incidents.map((q,i)=>`<label><input type="checkbox" data-key="threat.incidents.${i}"> ${h(q)}</label>`).join('');
 document.getElementById('recipientChecks').innerHTML=recipients.map((q,i)=>`<label><input type="checkbox" data-key="intelligence.recipients.${i}"> ${h(q)}</label>`).join('');
 document.getElementById('capabilityChecks').innerHTML=capabilities.map((q,i)=>`<label><input type="checkbox" data-key="intelligence.capabilities.${i}"> ${h(q)}</label>`).join('');
 document.getElementById('deliveryChecks').innerHTML=deliveries.map((q,i)=>`<label><input type="checkbox" data-key="intelligence.deliveries.${i}"> ${h(q)}</label>`).join('');
 document.getElementById('productChecks').innerHTML=products.map((q,i)=>`<label><input type="checkbox" data-key="intelligence.products.${i}"> ${h(q)}</label>`).join('');
 document.getElementById('controlCards').innerHTML=CONTROLS.map(c=>`<fieldset><legend><span class="pill">${c.id} · Tier ${c.tier} · ${c.h}h · ${c.c}</span> ${h(c.q)}</legend><p class="small"><strong>Done looks like:</strong> ${h(c.done)}</p><div class="radios">${['Yes','No','Not sure','Not applicable'].map(v=>`<label><input type="radio" name="control_${c.id}" value="${v}" data-key="controls.${c.id}"> ${v}</label>`).join('')}</div></fieldset>`).join('');
 renderTable('systemsTable','systems',['System','What it holds','Who administers it','Who else can log in','Second sign-in step on?'],['system','holds','admin','others','mfa']); renderTable('vendorsTable','vendors',['Vendor','What they hold or can do','Contact','Would they tell us if breached?'],['vendor','holds','contact','notice']); renderTable('accountsTable','accounts',['Person','Role','Has email','Can move money','Full admin rights','Still active?'],['person','role','email','money','admin','active']);
 const stages=['0. Intake — return intake form','1. Kickoff — agree on scope and worksheet due date','2. Self-assessment — worksheets and tool output received','3. Advisor review — report drafted','4. Readout — owner and three actions named','5. Day 90 check-in — actions completed or deferred with reason','6. Month 6 reassessment — compare indices'];document.getElementById('stages').innerHTML=stages.map((x,i)=>`<label><input type="checkbox" data-key="engagement.stages.${i}"> ${h(x)}</label><br>`).join('');
 document.getElementById('reviewChecks').innerHTML=['Check contradictions between answers','Identify a single person who is the only route into a critical system','Verify domain ownership and expiry using public information','Align top actions to the organization’s crown jewels'].map((x,i)=>`<label><input type="checkbox" data-key="engagement.review.${i}"> ${h(x)}</label><br>`).join('');
 document.getElementById('scopeCards').innerHTML=['Scanning or testing requires a separate written scope and authorization.','Hands-on fixes are outside this advisory engagement.','Never accept client credentials.','Suspected compromise stops the assessment and becomes incident response.','Provide the report to the organization; let it communicate with insurers or funders.'].map(x=>`<div class="card">${h(x)}</div>`).join('');
 document.getElementById('beforeChecks').innerHTML=['One-page engagement letter covers scope, no testing, no warranty, advisory-only, and report ownership','Professional liability coverage for unpaid advisory work checked','Active-compromise response decision documented','Worksheet handling and deletion schedule communicated'].map((x,i)=>`<label><input type="checkbox" data-key="engagement.before.${i}"> ${h(x)}</label><br>`).join('');
 bindInputs();
}
function renderTable(host,id,headers,fields){const root=clear(document.getElementById(host)),wrap=node('div',null,{class:'table-wrap'}),table=node('table'),thead=node('thead'),hr=node('tr');headers.forEach(x=>add(hr,node('th',x)));add(hr,node('th','Remove'));add(thead,hr);const tbody=node('tbody');(data.tables[id]||[]).forEach((row,i)=>{const tr=node('tr');fields.forEach((f,j)=>{const td=node('td'),input=node('input',null,{type:'text',maxlength:'800','aria-label':`${headers[j]} row ${i+1}`,'data-table':id,'data-row':i,'data-field':f});input.value=safeText(row[f]);add(td,input);add(tr,td)});const td=node('td');add(td,node('button','Remove',{type:'button',class:'danger remove-row','data-table':id,'data-row':i}));add(tr,td);add(tbody,tr)});add(table,thead,tbody);add(wrap,table);add(root,wrap,node('button','Add row',{type:'button',class:'secondary add-row','data-table':id}));bindTable(host)}
function bindTable(host){const el=document.getElementById(host);el.querySelectorAll('[data-field]').forEach(x=>x.addEventListener('input',e=>{const t=e.target;data.tables[t.dataset.table][+t.dataset.row][t.dataset.field]=t.value;markDirty()}));el.querySelectorAll('.add-row').forEach(x=>x.addEventListener('click',()=>{data.tables[x.dataset.table].push({});rerenderTables()}));el.querySelectorAll('.remove-row').forEach(x=>x.addEventListener('click',()=>{data.tables[x.dataset.table].splice(+x.dataset.row,1);rerenderTables()}))}
function rerenderTables(){renderTable('systemsTable','systems',['System','What it holds','Who administers it','Who else can log in','Second sign-in step on?'],['system','holds','admin','others','mfa']);renderTable('vendorsTable','vendors',['Vendor','What they hold or can do','Contact','Would they tell us if breached?'],['vendor','holds','contact','notice']);renderTable('accountsTable','accounts',['Person','Role','Has email','Can move money','Full admin rights','Still active?'],['person','role','email','money','admin','active']);markDirty();updateAll()}
function bindInputs(){document.querySelectorAll('[data-key]').forEach(el=>{if(!el.dataset.bound){el.addEventListener(el.type==='checkbox'||el.type==='radio'?'change':'input',e=>{if(e.target.type==='radio'&&!e.target.checked)return;set(e.target.dataset.key,e.target.type==='checkbox'?e.target.checked:e.target.value)});el.dataset.bound='true'}const v=get(el.dataset.key);if(el.type==='checkbox')el.checked=v===true;else if(el.type==='radio')el.checked=v===el.value;else if(v!==undefined&&document.activeElement!==el)el.value=v})}
function calc(overrides={}){let inherentTotal=0,resTotal=0,closed=0;const rows=PATHS.map(p=>{let impact=p.i,like=p.l;if(p.raise&&get('context.'+p.raise)){impact=Math.min(5,impact+1);like=Math.min(5,like+1)}const inherent=impact*like;let rem=1;CONTROLS.forEach(c=>{const ans=Object.prototype.hasOwnProperty.call(overrides,c.id)?overrides[c.id]:get('controls.'+c.id);if(ans==='Yes'&&c.r[p.id])rem*=1-c.r[p.id]});const residual=Math.max(inherent*.08,inherent*rem);inherentTotal+=inherent;resTotal+=residual;const ratio=residual/inherent;if(ratio<=.25)closed++;return {...p,inherent,residual,ratio,status:ratio<=.25?'Closed':ratio<.75?'Reduced':'Open'}});return {index:Math.round(resTotal/inherentTotal*100),closed,rows}}
function tier(){let reached=-1;for(let t=0;t<=3;t++){if(CONTROLS.filter(c=>c.tier===t).every(c=>get('controls.'+c.id)==='Yes'))reached=t;else break}return reached}
function recommendations(base){return CONTROLS.filter(c=>get('controls.'+c.id)!=='Yes'&&get('controls.'+c.id)!=='Not applicable').map(c=>{const next=calc({[c.id]:'Yes'});const delta=base.index-next.index;const cw=c.c==='$0'?0:c.c==='low'?1:2;return {...c,delta,next:next.index,priority:delta/(c.h/3+cw+1)}}).sort((a,b)=>b.priority-a.priority).slice(0,3)}
function selected(list,path){return list.filter((x,i)=>get(`${path}.${i}`)===true)}
function priorityFor(kind){if(kind==='pir')return 'High';if(get('profile.targetedAttention')==='Yes')return 'High';return 'Medium'}
function architectStore(){
 const held=assets.filter((a,i)=>get(`threat.assets.${i}.held`));const crown=assets.filter((a,i)=>get(`threat.assets.${i}.crown`));const systems=(data.tables.systems||[]).filter(x=>safeText(x.system));const vendors=(data.tables.vendors||[]).filter(x=>safeText(x.vendor));const sect=selected(sectors,'profile.sectors');const inc=selected(incidents,'threat.incidents').filter(x=>x!=='None known');const team=safeText(get('intelligence.requestingTeam'))||safeText(get('intake.owner'))||'Organization';const outputs=selected(products,'intelligence.products').join('; ')||'Plain-language action alert';const scope=[sect.join(', '),safeText(get('profile.primaryCountry')),safeText(get('profile.additionalRegions'))].filter(Boolean).join('; ');
 const girs=[],fcrs=[],iers=[],dirs=[],pirs=[],sirs=[];
 const addG=(id,req,desc,priority='Medium')=>girs.push({id,priority,req,desc});
 addG('GIR-001','Identify cyber threats relevant to the organization’s mission, sector, and operating context.',`Mission: ${safeText(get('intake.mission'))||'Not provided'}. Scope: ${scope||'Not provided'}.` ,priorityFor('gir'));
 addG('GIR-002','Identify threats to the organization’s critical information and services.',`Critical assets: ${(crown.length?crown:held).join('; ')||'Not identified'}.`,priorityFor('gir'));
 addG('GIR-003','Identify threats and vulnerabilities affecting technologies and service providers used by the organization.',`Systems: ${systems.map(x=>x.system).join('; ')||'Not identified'}. Vendors: ${vendors.map(x=>x.vendor).join('; ')||'Not identified'}.`,priorityFor('gir'));
 const fcr=(id,link,req,desc,type='External',dtype='Threat reporting')=>fcrs.push({id,link,priority:'Medium',coll:type,team,scope,dtype,output:outputs,req,desc});
 fcr('FCR-001','GIR-001','Collect reporting on campaigns targeting comparable nonprofit, NGO, or mission-driven organizations.',`Relevant sectors: ${sect.join('; ')||'Not identified'}.`);
 fcr('FCR-002','GIR-002','Collect reporting on threats to identified crown jewels, sensitive data, financial processes, and critical services.',`Assets: ${(crown.length?crown:held).join('; ')||'Not identified'}.`);
 fcr('FCR-003','GIR-003','Collect authoritative and credible reporting on active exploitation affecting used technologies and critical vendors.',`Technologies: ${systems.map(x=>x.system).join('; ')||'Not identified'}. Vendors: ${vendors.map(x=>x.vendor).join('; ')||'Not identified'}.`);
 iers.push({id:'IER-001',link:'GIR-001',priority:'Medium',scope,dep:'External advisories and trusted reports',dtype:'Campaign, sector, geography, actor behavior',req:'Extract targeted sectors, geographies, missions, tactics, and recommended actions.',desc:'Normalize information needed to determine organizational relevance.'});
 iers.push({id:'IER-002',link:'GIR-003',priority:'High',scope,dep:'Vendor advisories and vulnerability sources',dtype:'Product, version, CVE, exploitation status, mitigation',req:'Extract affected product, exploitation status, evidence, mitigation, and source.',desc:'Supports technology and vendor relevance matching.'});
 systems.forEach((x,i)=>{const n=String(i+1).padStart(3,'0');dirs.push({id:`DIR-${n}`,linkgir:'GIR-003',linkfcr:'FCR-003',priority:'Medium',datareq:safeText(x.system),dtype:'Technology or service',req:`Collect threat and vulnerability data relevant to ${safeText(x.system)}.`,desc:`What it holds or does: ${safeText(x.holds)||'Not documented'}. Administrator: ${safeText(x.admin)||'Not documented'}.`})});
 pirs.push({id:'PIR-001',priority:'High',req:'What current cyber threats require a decision or defensive action by this organization?',desc:`Focus on mission, critical assets, used technologies, critical vendors, and actionable mitigations. Most damaging: ${safeText(get('threat.mostDamaging'))||'Not provided'}.`});
 pirs.push({id:'PIR-002',priority:'High',req:'Are actively exploited vulnerabilities or campaigns affecting technologies or providers used by the organization?',desc:'Prioritize confirmed exploitation and specific defensive action over generic indicator volume.'});
 inc.forEach((x,i)=>{const n=String(i+1).padStart(3,'0');sirs.push({id:`SIR-${n}`,priority:'Medium',req:`What observable behaviors or indicators would help identify recurrence of ${x}?`,desc:'Provide technically usable observations only when the organization or its provider can act on them.'})});
 return {girs,fcrs,iers,dirs,pirs,sirs};
}
function renderIntelProfile(){const s=architectStore(),root=document.getElementById('intelOutput');if(!root)return;clear(root);add(root,node('div','Export format: CTI Intelligence Requirements Architect. Review before sharing.',{class:'warning'}));[['GIRs',s.girs],['FCRs',s.fcrs],['IERs',s.iers],['DIRs',s.dirs],['PIRs',s.pirs],['SIRs',s.sirs]].forEach(([label,items])=>{add(root,node('h4',`${label}: ${items.length}`));const ul=node('ul');items.forEach(x=>add(ul,node('li',`${x.id}: ${x.req}`)));add(root,ul)})}
function exportArchitectJSON(){const blob=new Blob([JSON.stringify(architectStore(),null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`CTI_Architect_Compatible_${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function updateAll(){const c=calc(),t=tier(), recs=recommendations(c);document.getElementById('indexScore').textContent=c.index;document.getElementById('pathsClosed').textContent=`${c.closed} / 16`;document.getElementById('tierReached').textContent=t<0?'Not yet Tier 0':`Tier ${t}`;document.getElementById('resultIndex').textContent=c.index;document.getElementById('resultClosed').textContent=`${c.closed}/16`;document.getElementById('resultTier').textContent=t<0?'—':t;document.getElementById('recommendations').innerHTML=recs.length?recs.map((r,i)=>`<div class="card"><h3>${i+1}. ${h(r.q)}</h3><p>${r.h} hours · ${h(r.c)} · modeled index change ${c.index} → ${r.next} (${r.delta} points)</p><p class="small">${h(r.done)}</p><div class="grid2"><label>Who does it?<input data-key="plan.actions.${i}.owner" maxlength="200"></label><label>By when<input data-key="plan.actions.${i}.date" type="date"></label></div></div>`).join(''):'<p>All modeled controls are in place or marked not applicable.</p>';bindInputs();document.getElementById('pathResults').innerHTML=`<table><thead><tr><th>ID</th><th>Path</th><th>Inherent</th><th>Residual</th><th>Status</th></tr></thead><tbody>${c.rows.map(p=>`<tr><td>${p.id}</td><td>${h(p.n)}</td><td>${p.inherent.toFixed(1)}</td><td>${p.residual.toFixed(1)}</td><td>${p.status}</td></tr>`).join('')}</tbody></table>`;const ns=CONTROLS.filter(x=>get('controls.'+x.id)==='Not sure');document.getElementById('notSureList').innerHTML=ns.length?ns.map(x=>`<li>${h(x.q)}</li>`).join(''):'<li>No controls are currently marked “Not sure.”</li>';const admins=(data.tables.accounts||[]).filter(x=>safeText(x.admin).toLowerCase()==='yes').length;const inactiveAdmin=(data.tables.accounts||[]).some(x=>safeText(x.admin).toLowerCase()==='yes'&&safeText(x.active).toLowerCase()==='no');document.getElementById('adminFinding').textContent=inactiveAdmin?'Urgent review: an inactive account appears to retain full administrator rights.':admins>2?`Finding: ${admins} people appear to hold full administrator rights; review and reduce to no more than two where feasible.`:'Administrator-rights count does not currently trigger the worksheet finding.';updateGate();renderReport(c,t,recs);renderIntelProfile();markComplete()}
function updateGate(){const reasons=[];if(get('intake.dangerPop')==='Yes')reasons.push('The organization serves a population for whom disclosure could cause physical danger; refer for a specialized threat model.');if(get('intake.authority')==='No')reasons.push('The internal owner lacks authority to make a small change or purchase.');if(get('intake.techHandler')==='Nobody')reasons.push('Nobody currently handles technology.');if(/currently being attacked|active compromise|compromised now/i.test(get('intake.prompted')||''))reasons.push('Possible active compromise is incident response, not this assessment.');document.getElementById('intakeGate').innerHTML=reasons.length?`<strong>Refer or pause:</strong><ul>${reasons.map(x=>`<li>${h(x)}</li>`).join('')}</ul>`:'No referral trigger identified from the current intake answers.'}
function renderReport(c,t,recs){const org=get('intake.orgName')||'[Organization]';const notSure=CONTROLS.filter(x=>get('controls.'+x.id)==='Not sure');const crown=assets.filter((a,i)=>get(`threat.assets.${i}.crown`));document.getElementById('reportContent').innerHTML=`<p class="print-only">Model version ${MODEL_VERSION} · Self-assessment, not an audit</p><h2>NONPROFIT SECURITY ASSESSMENT</h2><p><strong>${h(org)}</strong> · ${new Date().toLocaleDateString()} · Model ${MODEL_VERSION}</p><h3>1. In your own words</h3><ul><li>Most likely: ${h(get('threat.mostLikely')||'Not answered')}</li><li>Most damaging: ${h(get('threat.mostDamaging')||'Not answered')}</li><li>Least prepared for: ${h(get('threat.leastPrepared')||'Not answered')}</li></ul><p><strong>Crown jewels:</strong> ${crown.length?h(crown.join('; ')):'Not selected'}</p><h3>2. Where you stand</h3><p>Exposure index: <strong>${c.index}/100</strong> · Paths closed: <strong>${c.closed}/16</strong> · Maturity: <strong>${t<0?'Not yet Tier 0':`Tier ${t}`}</strong>.</p><p>This index describes modeled control coverage relative to this organization’s own baseline. It does not predict the probability of a breach and is not suitable for cross-organization benchmarking.</p><h3>3. Do these three things</h3>${recs.map((r,i)=>`<p><strong>${i+1}. ${h(r.q)}</strong><br>${r.h} hours · ${h(r.c)} · modeled index ${c.index} → ${r.next}. Owner: ${h(get(`plan.actions.${i}.owner`)||'TBD')} · Due: ${h(get(`plan.actions.${i}.date`)||'TBD')}</p>`).join('')||'<p>No remaining modeled recommendation.</p>'}<h3>4. Confirm these</h3>${notSure.length?`<ul>${notSure.map(x=>`<li>${h(x.q)}</li>`).join('')}</ul>`:'<p>No “Not sure” answers recorded.</p>'}<h3>5. What we are not worrying about yet</h3><p>Do not prioritize advanced monitoring, broad vulnerability scanning, dark-web monitoring, or complex endpoint detection ahead of unfinished foundational controls. Purchase decisions must match the organization’s capacity to operate and respond.</p><h3>6. What we measured</h3><p>This is a self-reported assessment of whether defined controls exist. Control configuration quality was not tested. Re-run the same model in six months and compare the organization to its own baseline.</p><p><strong>Next:</strong> Owner ${h(get('plan.owner')||'TBD')} · 90-day check ${h(get('plan.day90')||'TBD')} · Reassessment ${h(get('plan.month6')||'TBD')}</p>`}
function markComplete(){STEPS.forEach((s,i)=>{const b=document.querySelector(`[data-step="${i}"]`);if(i<stepIndex)b.classList.add('complete')})}
function showStep(i){stepIndex=Math.max(0,Math.min(STEPS.length-1,i));STEPS.forEach((s,n)=>s.classList.toggle('active',n===stepIndex));document.querySelectorAll('[data-step]').forEach((b,n)=>{if(n===stepIndex)b.setAttribute('aria-current','step');else b.removeAttribute('aria-current')});document.getElementById('prevBtn').disabled=stepIndex===0;document.getElementById('nextBtn').disabled=stepIndex===STEPS.length-1;window.scrollTo(0,0);data.meta.lastStep=stepIndex;markDirty();updateAll()}
function save(){try{data.meta.updated=new Date().toISOString();localStorage.setItem(STORAGE_KEY,JSON.stringify(data));document.getElementById('saveStatus').textContent=`Progress saved ${new Date().toLocaleTimeString()}`;document.getElementById('resumeText').textContent=`Saved progress found${data.meta.updated?' from '+new Date(data.meta.updated).toLocaleString():''}.`}catch(e){document.getElementById('saveStatus').textContent='Could not save progress';console.error('Storage unavailable',e)}}
function validateImport(o){inspectTree(o);if(!o||typeof o!=='object'||Array.isArray(o))throw new Error('Root must be an object');if(!o.meta||o.meta.modelVersion!==MODEL_VERSION)throw new Error(`Expected model version ${MODEL_VERSION}`);if(!o.responses||typeof o.responses!=='object'||Array.isArray(o.responses))throw new Error('Missing responses');if(!o.tables||typeof o.tables!=='object'||Array.isArray(o.tables))throw new Error('Missing tables');for(const k of ['systems','vendors','accounts']){if(!Array.isArray(o.tables[k])||o.tables[k].length>500)throw new Error(`Invalid ${k} table`);o.tables[k].forEach(r=>{if(!r||typeof r!=='object'||Array.isArray(r))throw new Error('Invalid row');Object.values(r).forEach(v=>{if(typeof v!=='string')throw new Error('Table values must be text');if(v.length>5000)throw new Error('Imported value too long')})})}return JSON.parse(JSON.stringify(o))}
function exportJSON(){const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`nonprofit-risk-assessment-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function reset(){if(!confirm('Erase the current assessment and its manually saved browser copy? This cannot be undone unless you exported JSON.'))return;localStorage.removeItem(STORAGE_KEY);location.reload()}
function loadSaved(){try{const raw=localStorage.getItem(STORAGE_KEY);if(raw){data=validateImport(JSON.parse(raw));document.getElementById('resumeText').textContent=`Saved progress found${data.meta.updated?' from '+new Date(data.meta.updated).toLocaleString():''}.`;rerenderTables();bindInputs();showStep(Number.isInteger(data.meta.lastStep)?data.meta.lastStep:1)}else showStep(1)}catch(e){alert('Saved data could not be loaded: '+e.message)}}
document.addEventListener('click',e=>{const b=e.target.closest('[data-step]');if(b)showStep(+b.dataset.step)});document.getElementById('prevBtn').onclick=()=>showStep(stepIndex-1);document.getElementById('nextBtn').onclick=()=>showStep(stepIndex+1);document.getElementById('saveBtn').onclick=save;document.getElementById('resumeBtn').onclick=loadSaved;document.getElementById('restartBtn').onclick=reset;document.getElementById('eraseBtn').onclick=reset;document.getElementById('exportBtn').onclick=exportJSON;document.getElementById('exportIntelBtn').onclick=exportArchitectJSON;document.getElementById('printBtn').onclick=()=>window.print();document.getElementById('copyReportBtn').onclick=async()=>{try{await navigator.clipboard.writeText(document.getElementById('reportContent').innerText);alert('Report text copied.')}catch(e){alert('Clipboard access is unavailable. Select and copy the report manually.')}};document.getElementById('importFile').addEventListener('change',e=>{const f=e.target.files[0];if(!f)return;if(f.size>5*1024*1024){alert('File is larger than 5 MB.');return}const r=new FileReader();r.onload=()=>{try{data=validateImport(JSON.parse(r.result));markDirty();rerenderTables();bindInputs();showStep(1);alert('Assessment imported. Click Save my progress so far if you want to store it in this browser.')}catch(err){alert('Import failed: '+err.message)}finally{e.target.value=''}};r.onerror=()=>alert('The file could not be read.');r.readAsText(f)});
renderStatic();try{const raw=localStorage.getItem(STORAGE_KEY);if(raw){const peek=JSON.parse(raw);if(peek.meta&&peek.meta.updated)document.getElementById('resumeText').textContent='Saved progress found from '+new Date(peek.meta.updated).toLocaleString();} }catch(e){}showStep(0);
