
(function(){'use strict';
const S={worker:null,summaries:[],filtered:[],analysis:null,selected:null,rowH:32,overscan:10};const $=id=>document.getElementById(id);function pane(id){const el=$(id);if(!el)console.warn(`#${id} not found`);return el}
function init(){S.worker=new Worker('worker.js');S.worker.onmessage=onWorker;document.querySelectorAll('.tabs button').forEach(b=>b.onclick=()=>tab(b.dataset.tab));$('file').onchange=async()=>{let f=$('file').files[0];if(f)parse(await f.arrayBuffer())};$('keylog').onchange=async()=>{let f=$('keylog').files[0];if(f)S.worker.postMessage({cmd:'keylog',text:await f.text()})};$('loadSample').onclick=()=>{status('Loading worker sample...','warn');S.worker.postMessage({cmd:'sample'})};$('runValidation').onclick=()=>S.worker.postMessage({cmd:'validate'});$('applyFilter').onclick=applyFilter;$('filter').onkeydown=e=>{if(e.key==='Enter')applyFilter()};$('virtualScroller').onscroll=renderVirtual;$('packetRows').onclick=e=>{let r=e.target.closest('tr[data-n]');if(r)selectPacket(+r.dataset.n)};$('exportJson').onclick=exportJson;$('clear').onclick=()=>location.reload();renderPluginPane();renderDetectionPane()}
function parse(buf){status('Parsing in worker...','warn');S.worker.postMessage({cmd:'parse',buffer:buf,options:{maxBytes:250*1024*1024}},[buf])}
function onWorker(e){let m=e.data;if(m.type==='parsed'){S.summaries=m.summaries;S.filtered=S.summaries;S.analysis=m.analysis;$('exportJson').disabled=false;$('summary').innerHTML=`Packets <b>${m.count}</b> · Streams <b>${m.analysis.streams.length}</b> · TLS <b>${m.analysis.tls.length}</b> · HTTP TX <b>${m.analysis.http.length}</b> · Detections <b>${m.analysis.detections.length}</b>`;$('warnings').className=m.warnings.length?'panel warnings':'panel warnings empty';$('warnings').innerHTML=m.warnings.length?m.warnings.map(esc).join('<br>'):'No warnings.';renderVirtual();renderAll();renderPluginPane(m.plugins,m.capability);status('Parsed','ok')}if(m.type==='details')renderDetails(m.details);if(m.type==='error')status(m.message,'err');if(m.type==='validation')renderValidation(m.results);if(m.type==='keylogLoaded'){$('warnings').className='panel warnings';$('warnings').textContent=`SSLKEYLOGFILE loaded: ${m.entries} entries. Capability: ${m.capability}`}}
function safe(name,fn){try{fn()}catch(e){console.warn(`${name} render skipped/failed`,e)}}function renderAll(){safe('TLS',renderTls);safe('HTTP',renderHttp);safe('HTTP/2',renderHttp2);safe('Expert',renderExpert);safe('Stats',renderStats);safe('Detections',renderDetectionPane)}
function tab(id){document.querySelectorAll('.tabs button').forEach(b=>b.classList.toggle('active',b.dataset.tab===id));document.querySelectorAll('.tab').forEach(t=>t.classList.toggle('active',t.id===id))}function status(t,k=''){$('status').textContent=t;$('status').className='pill '+k}
function applyFilter(){let q=$('filter').value.trim().toLowerCase();S.filtered=!q?S.summaries:S.summaries.filter(p=>JSON.stringify(p).toLowerCase().includes(q.replace(/\s*(==|contains|>|<)\s*/g,' ')));$('filterStatus').textContent=`Showing ${S.filtered.length} of ${S.summaries.length}`;renderVirtual()}
function renderVirtual(){let sc=$('virtualScroller'),rows=$('packetRows'),sp=$('virtualSpacer'),total=S.filtered.length,rowH=S.rowH,view=Math.ceil(sc.clientHeight/rowH)+S.overscan,start=Math.max(0,Math.floor(sc.scrollTop/rowH)-S.overscan),end=Math.min(total,start+view+S.overscan);sp.style.height=(total*rowH+40)+'px';$('packetTable').style.transform=`translateY(${start*rowH}px)`;$('visibleRange').textContent=` rows ${start+1}-${end} / ${total}`;rows.innerHTML=S.filtered.slice(start,end).map(p=>`<tr data-n="${p.number}" class="${p.number===S.selected?'selected':''}"><td>${p.number}</td><td>${rel(p)}</td><td>${esc(p.source)}</td><td>${esc(p.destination)}</td><td>${esc(p.protocol)}</td><td>${p.length}</td><td>${esc(p.info)}</td></tr>`).join('')||'<tr><td colspan="7" class="empty">No packets</td></tr>'}
function selectPacket(n){S.selected=n;renderVirtual();tab('details');document.querySelectorAll('.tabs button').forEach(b=>b.classList.toggle('active',b.dataset.tab==='details'));S.worker.postMessage({cmd:'dissect',number:n})}
function renderDetails(d){if(!d)return;pane('detailsPane').innerHTML=`<p><span class="badge">Lazy dissection</span> <span class="badge">Plugins: ${esc(d.pluginsApplied.join(', '))}</span></p>`+d.layers.map(l=>`<details class="layer" open><summary>${esc(l.name)}</summary><ul>${l.fields.map(f=>`<li><span class="fname">${esc(f[0])}:</span> ${esc(f[1])} <span class="range">[${f[2]}:${f[2]+f[3]-1}]</span></li>`).join('')}</ul></details>`).join('');pane('hexPane').textContent=d.hex}
function renderTls(){let a=S.analysis,p=pane('tlsPane');if(!a||!p)return;p.innerHTML=a.tls.map(t=>`<div class="box"><h3>${esc(t.key)}</h3><p><span class="badge">TLS decryption: ${esc(t.capability)}</span></p><h4>JA3 MD5</h4>${t.ja3.map(j=>`<pre>${esc(j.string)}\nMD5: ${esc(j.md5)}\nCiphers: ${esc((j.ciphers||[]).join(', '))}</pre>`).join('')||'<p class="empty">No JA3.</p>'}<h4>X.509 metadata</h4>${t.certificates.map(c=>`<div class="event">CN=${esc(c.commonName||'n/a')} O=${esc(c.organization||'n/a')} len=${c.length}<br>${esc(c.preview)}</div>`).join('')||'<p class="empty">No cert metadata.</p>'}</div>`).join('')||'<p class="empty">No TLS.</p>'}
function renderHttp(){let a=S.analysis,p=pane('httpPane');if(!a||!p)return;p.innerHTML=table(a.http,['streamKey','index','method','host','uri','status','contentType','request','response'])}
function renderHttp2(){let a=S.analysis,p=pane('http2Pane');if(!a||!p)return;p.innerHTML=a.http2.map(h=>`<div class="box"><h3>${esc(h.streamKey)}</h3><p><span class="badge">HPACK: ${esc(h.hpackCapability)}</span><span class="badge">QPACK: ${esc(h.qpackCapability)}</span><span class="badge">Encrypted H2: ${esc(h.encryptedInspection)}</span></p><p><span class="badge">Frames ${h.frames.length}</span><span class="badge">SETTINGS ${h.settings.length}</span><span class="badge">PING ${h.ping.length}</span><span class="badge">RST ${h.rstStream.length}</span><span class="badge">GOAWAY ${h.goaway.length}</span></p>${h.settings.map(f=>`<div class="event">${f.settings.map(s=>`${esc(s.name)}=${s.value}`).join(', ')}</div>`).join('')}${h.ping.map(f=>`<div class="event">PING opaque=${esc(f.opaque)}</div>`).join('')}${h.rstStream.map(f=>`<div class="event">RST stream=${f.streamId} error=${esc(f.errorName)}</div>`).join('')}${h.goaway.map(f=>`<div class="event">GOAWAY last=${f.lastStreamId} error=${esc(f.errorName)}</div>`).join('')}</div>`).join('')||'<p class="empty">No HTTP/2.</p>'}
function renderExpert(){let a=S.analysis,p=pane('expertPane');if(!a||!p)return;p.innerHTML=a.expert.map(e=>`<div class="finding"><b>${esc(e.summary)}</b><br>${esc(e.detail||'')}</div>`).join('')||'<p class="empty">No expert findings.</p>'}
function renderStats(){let a=S.analysis,p=pane('statsPane');if(!a||!p)return;p.innerHTML='<h3>Streams</h3>'+table(a.streams,['streamId','key','protocols','packets','bytes'])+'<h3>Detections</h3>'+table(a.detections,['id','severity','detail'])}
function renderPluginPane(plugins=[],cap={}){let p=pane('pluginPane');if(!p)return;plugins=plugins.length?plugins:[{name:'frame',order:0},{name:'ethernet',order:10},{name:'lazy-dissection',order:99}];p.innerHTML='<h3>Registered Dissector Plugins</h3>'+table(plugins,['order','name'])+'<h3>Capability States</h3>'+Object.entries(cap).map(([k,v])=>`<div class="box"><b>${esc(k)}</b>: ${esc(v)}</div>`).join('')}
function renderDetectionPane(){let p=pane('detectionPane');if(!p)return;let a=S.analysis;p.innerHTML='<p>Rule engine foundation supports rule objects with id, severity, matcher, and evidence output.</p>'+table(a?.detections||[],['id','severity','detail'])}
function renderValidation(r){let p=pane('validationPane');if(!p)return;p.innerHTML=r.map(x=>`<div class="${x.pass?'test-pass':'test-fail'}">${x.pass?'✓':'✗'} ${esc(x.name)} ${x.error?'— '+esc(x.error):''}</div>`).join('');tab('validation');document.querySelectorAll('.tabs button').forEach(b=>b.classList.toggle('active',b.dataset.tab==='validation'));status(r.every(x=>x.pass)?'Validation passed':'Validation failed',r.every(x=>x.pass)?'ok':'err')}
function exportJson(){download('packet-viewer-v3.0.1-analysis.json',{schema:'packet-viewer-v3.0.1-corrected',summaries:S.summaries,analysis:S.analysis})}
function table(rows,cols){return rows?.length?`<table><thead><tr>${cols.map(c=>`<th>${esc(c)}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${cols.map(c=>`<td>${esc(Array.isArray(r[c])?r[c].join(', '):(r[c]??''))}</td>`).join('')}</tr>`).join('')}</tbody></table>`:'<p class="empty">No data.</p>'}
function download(n,o){let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(o,null,2)],{type:'application/json'}));a.download=n;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}function rel(p){return S.summaries.length?(p.timestamp-S.summaries[0].timestamp).toFixed(6):''}function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}document.addEventListener('DOMContentLoaded',init)
})();
